slaclab/pysmurf

- base/smurf_control.py
- cfg_files/experiment_fp29_smurfsrv03_noExtRef_hbOnlyBay0.cfg
- debug/smurf_noise.py
- scratch/shawn/init_dev.py
- scratch/shawn/measureFluxRampFvsV.py
- scratch/shawn/pole/measureFluxRampFvsV_atPole.py
- tune/smurf_tune.py
- util/smurf_util.py
Shawn was working in this version with the HB on the NIST 7-8 GHz box we had installed in Frankenpolar in run 29.  For folks with access to the Frankenpolar pages in the SLAC SMuRF confluence, the best set of measurements to date taken with this branch are summarized here;
https://confluence.slac.stanford.edu/pages/viewpage.action?pageId=246770396
Nothing really substantial here, just some clean up and added documentation.  A quick summary of some notable things added in this branch;
- Configuration file cfg_files/experiment_fp29_smurfsrv03_noExtRef_hbOnlyBay0.cfg is the best one for running with the HB AMC on the NIST 7-8 GHz box in FP29.
- Big improvements to Shawn's SQUID curve measurement script - now supports taking data on multiple bands simultaneously, taking it vs amplitude with …
> Hb devel dspv2

- base/smurf_config.py
- cfg_files/pton/experiment_pc004_smurfsrv08_noExtRef.cfg
- scratch/shawn/band_filling_test.py
- scratch/shawn/init_pton.py
- scratch/shawn/measureFluxRampFvsV.py
- tune/smurf_tune.py
- util/smurf_util.py
Improvements to dspv2 pysmurf from Princeton running with a HB AMC on MMBv1pp.  
Including:
- Added ability to add comments to pysmurf cfg.
- Updates to Pton configs and startup scripts (for using dspv2 with a HB AMC).
- Added ability to estimate the phi0 rate (using meas_lms_freq in tracking_setup).
- Added toggle feedback function from dspv3 ; toggling feedback added as an option to track_and_check.
- Fix for flux_mod2 so that the carrier rate is only estimated from assigned channels.
- Improvements to flux_mod2.
> Updating master with latest improvements to dspv2 from Pton MMBv1pp HB testing

- cfg_files/stanford/smurf-srv03/experiment_fp30_srv03_rfsoc.cfg
- scratch/shawn/scripts/shawnhammer.sh
- scratch/shawn/scripts/shawnhammerfunctions.sh
Fixes pysmurf issue #74, a bug in release [v3.1.1](https://github.com/slaclab/pysmurf/releases/tag/v3.1.1) which was causing shawnhammer to crash when it attempted to setup (due to a typo in the `shelf_manager` argument provided to the `setup(...)` call.  Also checking in the pysmurf RFSOC cfg that we used successfully to run the RFSOC implementation of SMuRF for the first time the week of 7/22/19 in the Stanford lab.
> Fixes issue 74 and first check in of a working RFSoC-SMuRF cfg

- pysmurf/base/base_class.py
- pysmurf/base/smurf_control.py
- pysmurf/debug/smurf_iv.py
- pysmurf/debug/smurf_noise.py
- pysmurf/tune/smurf_tune.py
- pysmurf/util/pub.py
- pysmurf/util/smurf_util.py
This branch moves the publisher from SmurfControl to SmurfBase, since its used in all of the mix-in classes. I added a register_file function to the publisher that publishes all the correct data to UDP, and added a bunch of publish calls whenever I found a file being written. It might not be every file, but it'll be easy to add publish statements to additional files if I missed any.  
Also I took out the `publish` parameter which enabled publishing, since this is already enabled by setting the `SMURFPUB_BACKEND` environment variable to "udp". If that is not set, the publisher won't write anything.
> Publish calls

- README.md
This resolves #100. It describes how to build the documentation and view it locally. There is also a note about installation, which is needed for Sphinx to be able to build properly. I know the `setup.py` for packaging pysmurf is relatively new (688c344454568259251fe52f8a4e2191e88750cb), but it seems based on #101 that the `pip install` might not be totally sufficient for proper installation. Additional installation info should be added if needed.
As for the documentation style -- looking briefly at some of the docstrings it looks like a majority of them are closest to the Google Style, so I've gone with that and linked to the example in the napoleon docs that I find to be a useful reference when writing docstrings.
> Add install and docs build steps to README

- .readthedocs.yml
- README.md
- requirements.txt
- setup.py
The `setup.py` file didn't specify submodules within the pysmurf package. This PR updates setup.py to dynamically find these submodules.
@laurensaunders discovered that the docs wouldn't build properly given the instructions due to both the packaging issue and the lack of a `requirements.txt`. Here we also add this requirements file to specify package dependencies, and include a line in the installation instructions.
Finally, I had talked to @swh76 about setting up the documentation on readthedocs. This links to the docs using a badge at the top of the README, and adds a configuration file for the builds there. It'd be great to get a webhook setup so they autobuild on new commits, I'll be in touch with a repo admin about doing that. Happy to add someone as a maintainer on the readthedocs …
> Fix packaging and add readthedocs

- python/pysmurf/__init__.py
- python/pysmurf/core/devices/_SmurfApplication.py
Add __init__.py to pysmurf sub-dir so that it operates as a proper python package. 
Also restore pysmurf directory variable.
> Fix pysmurf package state

- include/smurf/core/transmitters/BaseTransmitter.h
- include/smurf/core/transmitters/BaseTransmitterChannel.h
- python/pysmurf/core/transmitters/_BaseTransmitter.py
- src/smurf/core/transmitters/BaseTransmitter.cpp
- src/smurf/core/transmitters/BaseTransmitterChannel.cpp
- src/smurf/core/transmitters/CMakeLists.txt
- src/smurf/core/transmitters/module.cpp
This PR channelizes the BaseTransmitter slave interface into separate data and meta data channels.
> Add meta data channel to base transmitter

- python/pysmurf/core/roots/CmbEth.py
- python/pysmurf/core/roots/CmbPcie.py
- python/pysmurf/core/utilities/_SetupGroups.py
- python/pysmurf/core/utilities/__init__.py
Here I have defined the streaming group to be 'stream'. Any variable in this group will be streamed to the data file and to the OCS back end. I have also created a utility script to define the variable list group and update the variable group membership on the startup of the root object.
> Setup stream group and add utility to define pysmurf groups

- python/pysmurf/client/util/SmurfFileReader.py
Here I have created a SmurfStreamReader class which can be used to process both new and old data formats, with meta data support. This also supports reading data broken into multiple files:
Example usage:
`````
with SmurfStreamReader(fileList,isRogue=True, metaEnable=True]) as fr:
for header,data in fr.records():
`````
> Smurf reader class

- python/pysmurf/core/roots/Common.py
- python/pysmurf/core/utilities/__init__.py
As it brings client dependencies.
Related to: https://jira.slac.stanford.edu/browse/ESCRYODET-447
> Temporary remove the Publisher from the server

- python/pysmurf/core/roots/Common.py
- python/pysmurf/core/utilities/_SmurfPublisher.py
- python/pysmurf/core/utilities/__init__.py
I suspect the API will end up being a bit different for the Rogue version of the publisher, so I have copied the publisher code into the Rogue interface.
> Create seperate Rogue Version of Publisher

- requirements.txt
Builds on readthedocs were failing silently due to maptlotlib not being in `requirements.txt`. This just adds it, fixing the documentation builds.
> Fix automatic documentation builds

- docker/server/Dockerfile
This new version has a rogue patch that was causing the root's close() methods to hang, as described here: https://jira.slac.stanford.edu/browse/ESCRYODET-471
> Update smurf-rogue image to version R2.3.1

- pysmurf/tune/smurf_tune.py
Adding some requested features to plot_tune_summary.  Now can disable the summary plot, plots include channels if assigned on them, and user can provide a restricted list of channels for the function to plot, instead of all resonances swept by setup_notches.
> Add tune summary features

- python/pysmurf/core/emulators/_DataFromFile.py
- python/pysmurf/core/emulators/__init__.py
- python/pysmurf/core/transmitters/_DataToFile.py
- python/pysmurf/core/transmitters/__init__.py
- src/smurf/core/processors/SmurfProcessor.cpp
- tests/validate_filter.py
There was a bug in the SmurfProcessor code, before the filter, which was processing the data in an incorrect way. 
The filter itself was implemented correctly. 
I added a validation script that generates random data, filters it using `scipy.signal.lfilter`, then sends the same data trough the SmurfProcessor with only the filter enabled, and with the same filter parameters used for the `scipy.signal.lfilter` filter and then compares the two results. It calculates the RMSE and verify that it is 0.
https://jira.slac.stanford.edu/browse/ESCRYODET-479
> Validate the SmurfProcessor's filter

- tests/validate_filter.py
When setting the SMuRF processor filter. Use the filter_order variable instead now.
> Bug fix: validate_filter.py was using a hard-code filter order of 4

- python/pysmurf/core/roots/Common.py
- server_scripts/emulate_local.py
Replaces a call to fifo.setSlave() with streamConnect() to prepare for an updated rogue version which removes setSlave().
> Use stream connect instead of setSlave

- docker/server/Dockerfile
https://jira.slac.stanford.edu/browse/ESCRYODET-497
> Update smurf-rogue base image to version R2.4.0

- docker/server/Dockerfile
https://jira.slac.stanford.edu/browse/ESCRYODET-502
> Update smurf-rogue base image to version R2.4.1

- docker/server/Dockerfile
The smurf-rogue base image was also updated to R2.5.0 in which Rogue is built in the same "RelWithDebInfo" mode as well.
https://jira.slac.stanford.edu/browse/ESCRYODET-519
> Build pysmurf in "RelWithDebInfo" mode to have debug symbols 

- include/smurf/core/processors/SmurfProcessor.h
- include/smurf/core/transmitters/DualDataBuffer.h
of the mutex they use, so that the mutex already exist when they are used. 
https://jira.slac.stanford.edu/browse/ESCRYODET-526
> Bug fix: Move declaration of the std::thread to after the declaration 

- docker/server/Dockerfile
This version include this [bug fix](https://github.com/slaclab/rogue/pull/602) in Rogue that was causing a deadlock as reported in [ESCRYODET-533](https://jira.slac.stanford.edu/browse/ESCRYODET-533)
> Update smurf-rogue base image to version R2.5.1

- python/pysmurf/core/roots/CmbEth.py
- python/pysmurf/core/roots/CmbPcie.py
- python/pysmurf/core/roots/Common.py
- python/pysmurf/core/server_scripts/_VariableGroupExample.py
- python/pysmurf/core/utilities/_SetupGroups.py
- server_scripts/cmb_eth.py
- server_scripts/cmb_pcie.py
startup script. And move the current definition to a separate file
as an example.
> Expose and interface to define the VariableGroups from the top server

- python/pysmurf/client/util/smurf_util.py
This PR just disables streaming when `stream_data_off` is called. This is to prevent data from being sent to the smurf-streamer when users don't want to be streaming data.
> Disable streamEnable on stream_data_off

- python/pysmurf/core/server_scripts/Common.py
This PR changes the common argument parsing method from get_opt to argparse, so that it is more versatile and can be used by SO streaming scripts. The argument parsing is split into `make_parser` which returns a parser with all of the smurf arguments added to it, and `process_args`, which takes an args namespace and does the processing.
I left in the `get_args` function, and made it parse and process the args, and return the argument namespace as a dict, so it should still work with existing code that used that function, but I haven't tested it yet.
I have tested it with my scripts, and I'm able to do things like add my own arguments to the parser before parsing, and pre-processing the command line arguments before passing them to the parser.
Let me know if there are any changes you think …
> Changed common argument parsing to use argparse

- python/pysmurf/client/util/smurf_util.py
Bay 0 uses Stream0 and Stream1.  Bay 1 uses Stream2 and Stream3.  Need to parse file header to determine which stream is f and which is dF.  This works for bay 1, need to confirm bay 0 still works as well.
*       headerA:
*          [31:0] = Length of data block in bytes
*       headerB
*          31:24  = Channel ID
*          23:16  = Frame error
*          15:0   = Frame flags
> Properly decode f, dF streams for either bay0 or bay1

- python/pysmurf/core/roots/Common.py
https://jira.slac.stanford.edu/browse/ESCRYODET-582
> Add workaround: set the "SmurfProcessor.ChannelMapper.Mask" to [0] by default

- python/pysmurf/core/roots/Common.py
and fix the usage of the epics module after import, it was being
used incorrect, and triggering the flake8 error
> Add missing import which was remove during flake8 cleanup

- python/pysmurf/core/roots/CmbPcie.py
This is required to avoid lockups when generating large bursts from the DDR memory.
> Disable zero copy on DDR streams

- docker/server/Dockerfile
This will update Rogue to version v4.10.6, which has bug fixes we need. Specifically it has a bug fix for the PyDM interface Mitch discovered, described here: https://jira.slac.stanford.edu/browse/ESCRYODET-600
> Update smurf-rogue base image to version R2.6.1

- python/pysmurf/client/debug/smurf_iv.py
- python/pysmurf/client/util/smurf_util.py
This issue resolves #289 by adding the `register_file` argument to `stream_data_off`. When specified, the `.dat` file created during the streaming session will be registered with the publisher. The idea is that we want to archive smurf-data for most pysmurf functions including tuning and iv, but don't want to archive data when we are streaming for arbitrary lengths of time.
> Add argument to publish streamed data file 

- docker/server/scripts/server_common.sh
- docker/server/scripts/start_server.sh
This PR just changes the formatting of some log messages coming from the `pysmurf-server`'s `start_server.sh` script so that the output is homogenous. The output will look like this:
```
IP address was not defined. It will be calculated automatically from the crate ID and slot number...
Reading Crate ID via IPMI...                      Create ID: 0001.
Calculating FPGA IP address...                    FPGA IP: 10.0.1.105.
Looking for pyrogue zip file...                   Pyrogue zip file found: '/tmp/fw/rogue_MicrowaveMuxBpEthGen2_v0.0.3.zip'.
Looking for mcs file...                           Mcs file found: MicrowaveMuxBpEthGen2-0x00000020-20191203110805-mdewart-83947a3.mcs.gz
Reading FW Git Hash via IPMI...                   Firmware githash: '83947a3'.
Reading MCS file Git Hash... …
```
> Fix formatting of the log message from the start_server.sh

- docker/server/scripts/server_common.sh
- python/pysmurf/core/devices/_SmurfApplication.py
under the SmurfApplication device. With this change there are these 2 new registers: 
- **<epics_prefix>:AMCc:SmurfApplication:StartupScript** : name of the startup script used to start the pysmurf-server
- **<epics_prefix>:AMCc:SmurfApplication:StartupStartupArguments** : list of arguments passed to the startup script
For example:
```
cryo@smurf-srv13:/$ caget -S smurf_server_s5:AMCc:SmurfApplication:StartupScript
smurf_server_s5:AMCc:SmurfApplication:StartupScript /usr/local/src/pysmurf/server_scripts/cmb_pcie.py
cryo@smurf-srv13:/$ caget -S smurf_server_s5:AMCc:SmurfApplication:StartupArguments
smurf_server_s5:AMCc:SmurfApplication:StartupArguments -g -w smurf_server_s5 -e smurf_server_s5 -d /tmp/fw/config/defaults.yml -l 3 -a 10.0.1.105 -z …
```
> Expose the server startup script name and list of arguments

- cfg_files/stanford/fp30_smurf_startup.cfg
- scratch/shawn/scripts/shawnhammer.sh
- scratch/shawn/scripts/shawnhammerfunctions.sh
shawnhammer now detects when the pysmurf server is up by waiting until it gets a valid timestamp from the server (smurf_server_s#:AMCc:LocalTime) and that timestamp is incrementing in both serial and parallel bootup modes.  Previously shawnhammer detected server up by looking for a print statement in the rogue docker, which has already broken a couple of times when that print statement was changed.  The print statement shawnhammer used to parse was the "GUI is up" print statement, so now shawnhammer can detect the server is up even if the GUI is not enabled, and can setup faster, since it seems like the server often comes up before the GUI does.  Also fixes an issue with attaching at the end of pysmurf setup ; the function in shawnhammer that detects when pysmurf is done setting up (by …
> Fix shawnhammer smurf server detection

- python/pysmurf/core/roots/EmulationRoot.py
- python/pysmurf/core/server_scripts/Common.py
- server_scripts/emulate.py
This PR adds a default server_port in the process_args function. This is to support running in emulation mode when neither the pcie_rssi_lane or the ip address is defined.
> Adds default server_port when IP Address is not defined

- server_scripts/cmb_eth.py
- server_scripts/cmb_pcie.py
The bug in the `EM22xx` device was fixed (see [ESCRYODET-614](https://jira.slac.stanford.edu/browse/ESCRYODET-614)), so we can re-enable this flag.
The [current ZIP file](https://github.com/slaclab/cryo-det/releases/download/MicrowaveMuxBpEthGen2_v0.0.3/rogue_MicrowaveMuxBpEthGen2_v0.0.3.zip) doesn't include the fixes needed for this device to work, so it won't show in the rogue tree, but the system will run normally. The only difference is that there will be this warning message in the server's log:
```
TypeError calling FpgaTopLevel: __init__() got an unexpected keyword argument 'enablePwrI2C'
This FpgaTopLevel does not support the option 'enablePwrI2C'.
Please use a pyrogue zip file which is up to date.
Staring the server without using the 'enablePwrI2C' option.
```
After the …
> Re-enable the "enable_em22xx" flag from the top script.

- .github/labeler.yml
- .github/workflows/label.yml
This PR fixes issue #320 by setting the GitHub labeler workflow to automatically add the labels `core` or `client` depending on the section of the code the PR modifies, as defined in the `.github/labeler.yml` file
> Setup Github workflow to auto label PR as `core` or `client`

- .github/workflows/verify-pr-labels.yml
This PR solved #321.
It adds the GitHub actions [verify-pull-request-labels](https://github.com/marketplace/actions/verify-pull-request-labels) to verify that all PRs have at least one of these labels before they can be merged: `bug`, `enhancement`, `interface-change`.
This action works around the issue I mentioned in #321 regarding checks trigger with different conditions, and instead works in the following way:
- If a PR does not have one of the valid labels, then the Github check will succeed, but it will create a pull request review, requesting for changes. This will prevent the PR to be merge until the review is addressed. 
- If a PR have at least one valid label, then the Github check will also succeed, and it will create a pull request review, approving it. This will clear the …
> Verify that all PRs are labeled with `bug`, `enhancement`, or `interface-change`

- docker/client/Dockerfile
- docker/server/Dockerfile
This PR resolves #324.
The base docker image `smurf-base` didn't contained the home directory for the cryo user. So, when the container was  running the directory `/home/cryo` didn't exit. It seems that ipython write access to the home directory for its tab complete feature to work. That was fix in this [PR](https://github.com/slaclab/smurf-base-docker/pull/2), which is available in version [tidair/smurf-base:R1.1.1](https://github.com/slaclab/smurf-base-docker/releases/tag/R1.1.1). 
This was affecting only the client docker image. However, I updated its base docker image as well to include that fix. It is available in the version [tidair/smurf-rogue:R2.6.2](https://github.com/slaclab/smurf-rogue-docker/releases/tag/R2.6.2).
In this PR I update the two base docker images to these new …
> Fix `pysmurf-client` docker image, by adding the cryo user's home directory

- python/pysmurf/client/base/smurf_control.py
In this case this was done during `SmurfControl.setup`, but this is not allowed in general.
In this case we can set the Mask to an single element `[0]` instead. 
This resolves #335 .
> Bug fix: trying to set a register to an empty array is not supported

- setup.cfg
- setup.py
This fixes the setup.py and setup.cfg files to work with the new rogue4 file structure.  Resolves issue https://github.com/slaclab/pysmurf/issues/341.
> Fixes setup.py to reflect rogue4 change in pysmurf code directory structure

- python/pysmurf/client/debug/smurf_iv.py
- python/pysmurf/client/util/smurf_util.py
https://github.com/slaclab/pysmurf/issues/340
The problem is that overbias_tes ends in high_current_mode by default. In general, we should not have functions that leave the state of the TES bias in high_current_mode since it heats the FPU.
> Changing default of high_current_mode in overbias_tes

- setup.cfg
PR https://github.com/slaclab/pysmurf/pull/342 didn't quite fix issue https://github.com/slaclab/pysmurf/issues/341.  This PR finishes addressing issue https://github.com/slaclab/pysmurf/issues/341 ; the location of _version.py was not correctly specified in setup.cfg for the new rogue4 code directory structure.
> Fixes location of version_file in pysmurf package setup.cfg

- docs/base.rst
- docs/command.rst
- docs/debug.rst
- docs/index.rst
- docs/tune.rst
- docs/util.rst
- requirements.txt
Adjusted paths in the docs/*.rst files to reflect change in pysmurf code directory structure in rogue 4.  Added pyyaml module to the required dependencies (imported in utils).  Autogenerated documentation can be accessed here again now - https://pysmurf.readthedocs.io/en/master/.  Fixes #349
> Fixes readthedocs auto builds

- python/pysmurf/client/debug/smurf_noise.py
- python/pysmurf/client/tune/smurf_tune.py
- python/pysmurf/client/util/smurf_util.py
- scratch/eyy/test_scripts/profile_band.py
This PR resolves #353 
This PR also:
- updated the doc strings for `tune_band_serial` and `noise_vs_tone` to be consistent with numpy conventions.
- Added convenience function for sample_freq
- Adds testing threading to `profile_band.py`
> Fixes the noise_vs_tone function. The plotting routine had a bug in it which would cause it to crash.

- .github/CODEOWNERS
This PR resolves #359 
With this PR Ed, Shawn, Ryan and I will all be code owner of the GitHub related scripts, which defined setting of the repository like for example issues and PR templates. 
I think it make sense for all of us to be owner and be able to approve PR for this section.
> Add Ed and Shawn as code owner of GitHub files

- python/pysmurf/client/debug/smurf_noise.py
This PR resolves https://github.com/slaclab/pysmurf/issues/366 
This fixes the plotting routine in `noise_vs_tone`. It properly selects the correct channel from the mask file. It doesn't plot channels that are not taken.
> Fixes the `noise_vs_tone` analysis script - wasn't handling channel assignment properly

- python/pysmurf/client/tune/smurf_tune.py
- python/pysmurf/client/util/smurf_util.py
https://github.com/slaclab/pysmurf/issues/369
The function `identify_bias_group` does not have the ability to go to `low_current_mode`.
This also changes the plot labels for `tracking_setup` to include more information.
Adds the boolean `high_current_mode` to `identify_bias_group` to allow the user to attempt to identify bias groups using either high or low current TES mode.
> Adding high_current_mode bool to identify_bias_group

- cfg_files/stanford/experiment_fp30_cc02-03_lbOnlyBay0.cfg
- python/pysmurf/client/debug/smurf_noise.py
- python/pysmurf/client/util/smurf_util.py
This PR resolves #371 
This adds the optional variable `overbias_wait` to `noise_vs_bias`.
> Adding overbias_wait to noise_vs_bias

- .travis.yml
- docs/conf.py
- python/pysmurf/core/devices/_PcieCard.py
This PR resolves #382 
This PR adds a travis job under the test stage to run the sphinx documentation build and to fail on errors and warnings.
> Add travis job to test documentation build for errors and warnings

- python/pysmurf/client/util/smurf_util.py
This PR doesn't resolve any posted issues.
Reproduces code in @ccffccffcc's PR https://github.com/slaclab/pysmurf/pull/331, which we weren't able to add labels too because it was a fork.
> Use list instead of np.array in read_stream_data for speed up.

- python/pysmurf/client/command/smurf_command.py
- python/pysmurf/client/util/tools.py
Resolves issue https://github.com/slaclab/pysmurf/issues/399.
Eliminates all the utf8 byte array caget return types (epics caget calls return utf8 byte arrays for string-type variables unless passed `as_string=True` option).  
- Added `**kwargs` to `_caget` and `_caput`.  Gets passed directly into the `caget` and `caput` calls.
- Added `as_string=True` to get_rogue_version `_caget call`, eliminated `as_str` input ; 
option no longer provided for utf8 byte array return type.  Updated function docstring.
- Added `as_string=True` to `get_streamdatawriter_datafile` `_caget` call, eliminated `as_str` input ; 
option no longer provided for utf8 byte array return type.  Updated function docstring.
- Eliminated conversion from UTF-8 byte array to str in `get_tone_file_path` function in favor 
of …
> Eliminates utf8 byte array return type option for str register gets.

- python/pysmurf/client/base/base_class.py
- python/pysmurf/client/base/smurf_control.py
- python/pysmurf/client/command/smurf_command.py
- python/pysmurf/client/util/smurf_util.py
Resolves issue https://github.com/slaclab/pysmurf/issues/398.
pysmurf has been guessing at which AMC bays are usable by which bands are present in the pysmurf cfg file.  This PR adds a `which_bays` routine to utils which parses the pysmurf server startup arguments to determine which bays were disabled on startup.
- Adds `get_pysmurf_version`, `get_pysmurf_directory`, `get_smurf_startup_script`, and `get_smurf_startup_args` routines to `smurf_command` module for querying SmurfApplication registers.
- Adds a `which_bays` routine to `smurf_utils` module which determines which AMC bays were enabled on pysmurf server startup by parsing the pysmurf server startup options (using the new `get_smurf_startup_script` routine) for the presence of the `--disable-bay0` and `--disable-bay1` options.
- …
> Determine which bays are on from hardware, not pysmurf cfg.

- .flake8
- .travis.yml
- python/pysmurf/client/base/base_class.py
- python/pysmurf/client/base/smurf_control.py
- python/pysmurf/client/debug/smurf_iv.py
- python/pysmurf/client/debug/smurf_noise.py
- python/pysmurf/client/tune/smurf_tune.py
- python/pysmurf/client/util/smurf_util.py
- python/pysmurf/core/devices/_PcieCard.py
- python/pysmurf/core/devices/_SmurfProcessor.py
This PR is required to issue resolve https://github.com/slaclab/pysmurf/issues/395.
This PR fixes some minor RST errors throughout the pysmurf client and core docstrings.  After this PR is merged, we will pass the flake8 checks added by the flake8-rst-docstrings which validates the RST in all docstrings.
```
pip3 install flake8-rst-docstrings
flake8 --rst-roles class,func,ref --rst-directives envvar,exception
```
and we should add the flake8-rst-docstrings extension in the travis flake8 checks to maintain compliance.
> Fixes docstrings to have valid reStructuredText (RST)

- python/pysmurf/client/util/smurf_util.py
This PR resolves #408.
Changes which mask.txt file is registered by the pysmurf publisher
> Changed publish location for mask.txt file

- python/pysmurf/client/debug/smurf_iv.py
- python/pysmurf/client/tune/smurf_tune.py
- python/pysmurf/client/util/pub.py
- python/pysmurf/client/util/smurf_util.py
- scratch/jack/pub_listener.py
This PR is to solve the OCS problem for how we should be storing archived pysmurf data. From the workshop, we decided that a good system would be to group together all files for a given action. For instance, if you call S.find_freq, you might naturally want all outputs and plots to be grouped together under something like `smurf_dir/find_freq_1584335008/outputs` and `smurf_dir/find_freq_1584335008/plots`.
The way this worked before was that each `register_file` call was passed a "file type" such as "mask", which was used to group files. This didn't really work since functions like `find_freq` would call other functions, and so even though you only issued one command they would multiple groups.
The `set_action` decorator solves this by making the top-level function call set the action and …
> Publisher actions

- .flake8
- .travis.yml
- python/pysmurf/client/base/logger.py
- python/pysmurf/client/base/schema.py
- python/pysmurf/client/base/smurf_config.py
- python/pysmurf/client/base/smurf_config_properties.py
- python/pysmurf/client/base/smurf_control.py
- python/pysmurf/client/command/smurf_atca_monitor.py
- python/pysmurf/client/command/smurf_cmd.py
- python/pysmurf/client/command/smurf_command.py
- python/pysmurf/client/debug/smurf_iv.py
- python/pysmurf/client/debug/smurf_noise.py
- python/pysmurf/client/tune/smurf_tune.py
- python/pysmurf/client/util/listen.py
- python/pysmurf/client/util/pub.py
- python/pysmurf/client/util/smurf_util.py
- python/pysmurf/client/util/tools.py
- python/pysmurf/client/watchdog/JesdWatchdog.py
- python/pysmurf/core/devices/_PcieCard.py
- python/pysmurf/core/roots/Common.py
- python/pysmurf/core/utilities/_SmurfPublisher.py
This PR resolves https://github.com/slaclab/pysmurf/issues/419 and partially addresses https://github.com/slaclab/pysmurf/issues/397.
The main purpose of this PR is to add all of the docstrings for the SmurfConfig class, but it includes some minor bug fixes, a lot of linting, and a lot of cleanup (mostly aesthetic).
- Adds complete docstrings for smurf_config submodule.
- Now using only fstring formatting for all of pysmurf client and core code.
- Adds flake8-sfs module with directive to enforce fstring string formatting.
- Resolves nearly every flake8-docstrings warnings for the smurf_config submodule.
- `SmurfConfig.read()` now returns the loaded configuration dictionary, resolving issue https://github.com/slaclab/pysmurf/issues/419.
- Changes sphinx references to be auto-numbered.
- …
> Comprehensive docstrings for SmurfConfig class.

- cfg_files/stanford/fp30_smurf_startup.cfg
- python/pysmurf/client/command/smurf_cmd.py
- python/pysmurf/client/debug/smurf_iv.py
- python/pysmurf/client/debug/smurf_noise.py
- python/pysmurf/client/tune/smurf_tune.py
- python/pysmurf/client/util/smurf_util.py
- scratch/shawn/scripts/shawnhammer.sh
- scratch/shawn/scripts/shawnhammerfunctions.sh
- scratch/shawn/tune_1000x_nist.py
This PR resolves issue https://github.com/slaclab/pysmurf/issues/407.
A third optional column in the slot_cfgs table in smurf_startup.cfg can be used instead of a pysmurf init script.  If the pysmurf experiment.cfg is specified for one slot, it must be specified for all slots.  If it's not specified, shawnhammer will look for an init script specified by the `pysmurf_init_script` variable in smurf_startup.cfg (so this change is backwards compatible with using a pysmurf init script).  If both the column of pysmurf experiment.cfg files and the `pysmurf_init_script` variable is defined, the `pysmurf_init_script` variable will be ignored.
pysmurf object instantiation is now done with a new function called `pysmurf_init` in shawnhammerfunction.sh, which replicates what was previously done by …
> pysmurf cfg file can be specified in smurf_startup.cfg, no longer requiring an init script.

- README.md
- python/pysmurf/client/debug/smurf_noise.py
- python/pysmurf/client/tune/smurf_tune.py
- python/pysmurf/core/emulators/_DataFromFile.py
This is a trivial correction to the README.md file relating to docstrings.
Changes readthedocs badge in README.md file to master instead of latest (which we're not using right now).  Corrects README.md to say we use PyNumpy docstring conventions, not google docstrings conventions.
> Fixes readthedocs badge and docstring convention note in README.

- python/pysmurf/client/command/smurf_command.py
- python/pysmurf/client/util/smurf_util.py
- python/pysmurf/core/devices/_SmurfApplication.py
- python/pysmurf/core/roots/CmbEth.py
- python/pysmurf/core/roots/CmbPcie.py
- python/pysmurf/core/roots/Common.py
This PR resolves #427.
This adds a rogue variable `EnabledBays` to the Common root, which is a list of bays that are enabled, and switches `S.which_bays()` to check this variable instead of checking for `--disable-bayX` in the command line args. I've tested at UCSD.
> Create new rogue variable `EnabledBays` with a list of enabled bays

- python/pysmurf/client/util/smurf_util.py
This PR resolves #439.
Adds backwards compatibility to the which_bays function
> Backwards compatibility fix for which_bays

- python/pysmurf/client/util/smurf_util.py
Reverts slaclab/pysmurf#440.  I missed the comment in the PR that it hadn't yet been tested.  Still broken.
> Revert "Backwards compatibility fix for which_bays"

- scratch/shawn/deterministic_latency.py
- scratch/shawn/full_band_response.py
- scratch/shawn/scripts/loop.sh
- scratch/shawn/scripts/shawnhammer.sh
There's no existing pysmurf issue corresponding to this PR ; this adds a test to pysmurf to help address [ESCRYODET-671](https://jira.slac.stanford.edu/browse/ESCRYODET-671).
Adds new script, scratch/shawn/deterministic_latency.py, which runs an eta scan on a full subband in all configured bands so you can compare orientation of complex IQ data for successive system reboots.  Should be stationary, but it's currently not, so trying to track down why.  Here's a plot of running this script after rebooting two times in succession:
Also fixes a minor error in shawnhammer ; the `script_to_run` parameter wasn't implemented correctly (would always run scratch/shawn/test_new_carrier.py instead of the requested script).
> Adds test script to help check for deterministic latency & fixes script_to_run bug in shawnhammer.

- docker/server/scripts/server_common.sh
- python/pysmurf/client/command/smurf_command.py
- python/pysmurf/core/roots/Common.py
This PR resolves [ESCRYODET-667](https://jira.slac.stanford.edu/browse/ESCRYODET-667).
This PR includes some fixes and new features to help solve the configuration issue described in [ESCRYODET-667](https://jira.slac.stanford.edu/browse/ESCRYODET-667):
- Add extra checking while loading defaults: check the final status of the elastic buffer latency. Also, verify the return value and catch any exception from the `LoadConfig` command.
- Increase the rogue timeout from 1s to 5s.
- Increase the `wait_after` period for the set defaults and read all pysmurf client commands. With the previous periods, the commands were returning before the server finished the operations.
- Increase the timeout between deactivate and activate IPMI commands  during the `rebootFPGA` function.
> Add checks and fixes to help solve configuration issues

- cfg_files/stanford/fp30_smurf_startup.cfg
- python/pysmurf/client/command/smurf_command.py
This PR resolves issue https://github.com/slaclab/pysmurf/issues/449.
Adds docstrings to the smurf_command submodule `get_flux_ramp_freq` and `get_flux_ramp_freq` functions.  Fixes incorrect hardcoded clock rate assumed for `RampMaxCnt` in `get_flux_ramp_freq` (was 3.0725E5, but should be 3.072E5).  Added new `_ramp_max_cnt_clock_hz` attribute to the `SmurfCommandMixin` class that 
`get_flux_ramp_freq` and `set_flux_ramp_freq` both get the clock rate from.  This is still a hardcode, but at least now they'll both be forced to compute the flux ramp reset rate from the same base clock rate.  We could compute on the fly from the digitizer frequency, but then it's not possible to easily check if the flux ramp rate is an integer divisor of the clock rate due to precision error.
Fixed incorrect …
> Fixes wrong hardcoded clock rate in get_flux_ramp_freq, adds docstrings to get_flux_ramp_freq and set_flux_ramp_freq.

- docker/server/scripts/server_common.sh
- docker/server/scripts/start_server.sh
This PR resolves #434 
This PR:
- moves the argument parsing code from the `start_server.sh` script to the `server_common.sh`, to a function called `arg_parser()`. 
- moves the `usage()` function from the `start_server.sh` script to the `server_common.sh`.
- Updates the `start_server.sh` script to call these function from `server_common.sh`.
With these changes, other user can write their own `start_server.sh` function while still using all the common function we keep updated in `server_common.sh`
> Move the `start_server.sh` argument parsing and usage function to `server_common.sh`

- python/pysmurf/core/devices/_SmurfApplication.py
- python/pysmurf/core/roots/Common.py
This PR includes new features which help resolving [ESCRYODET-671](https://jira.slac.stanford.edu/browse/ESCRYODET-671).
This PR changes the wait we were testing the elastic buffers. We now check that the register for lanes 2,3 must be equal to 255, and all the other lanes must be either 13 or 14. Also, one when the check fails, instead of trying to execute `AppTop.Init()`, we instead try to reload the default configuration. 
Additionally, I added I new variable `SystemConfigured` under the `SmurfApplication` device. This variable will indicate if the configuration method `_set_defaults_cmd` was able to successfully load the configuration.
I added I new variable `SystemConfigured` under the `SmurfApplication` device. This change doesn't brake any interfaces, instead adds a new variable to …
> Update elastic buffer check, and add new variable `SystemConfigured`

- docker/server/Dockerfile
This updates rogue to version v4.11.2
This PR resolves [ESCRYODET-640](https://jira.slac.stanford.edu/browse/ESCRYODET-640).
This PR updates rogue to version v4.11.2. This version fixes a memory leak bug which was reported in [ESCRYODET-640](https://jira.slac.stanford.edu/browse/ESCRYODET-640).
> Update smurf-rogue base image to version R2.8.1

- cfg_files/rflab/rflab_smurf_startup.cfg
- python/pysmurf/client/base/smurf_control.py
- python/pysmurf/client/command/smurf_command.py
- scratch/shawn/rf_deterministic_latency.py
- scratch/shawn/scripts/shawnhammer.sh
- scratch/shawn/scripts/shawnhammerfunctions.sh
This PR resolves issue https://github.com/slaclab/pysmurf/issues/462.
This PR mostly expands the `smurf_command.set_defaults_pv` routine to check if loading the hardware defaults succeeded using the new `ConfiguringInProgress` and `SystemConfigured` registers described in https://github.com/slaclab/pysmurf/issues/462.  These new registers are not provided in the current stable pysmurf release (v4.0.0) so to use them right now, you have to run with a dev_sw rogue docker with the below version of pysmurf.  Here's an attempt at a comprehensive list of changes made:
* Added new `get_configuring_in_progress` and `get_system_configured` routines to `smurf_command` to poll the new `ConfiguringInProgress` and `SystemConfigured` registers.
* Adjusts the RF lab configuration files to use the newer …
> Use new registers which give the state of the configuration process during setup

- python/pysmurf/client/command/cryo_card.py
- scratch/eyy/test_scripts/page_template/index.html
- scratch/eyy/test_scripts/profile_band.py
This PR resolves https://github.com/slaclab/pysmurf/issues/483.
profile_band now takes 60 second noise PSDs after plotting the IV curves, and displays the PSD plots in the html page.
> Added noise PSD plots to profile_band.

- docs/client/command.rst
- python/pysmurf/client/base/smurf_control.py
- python/pysmurf/client/command/smurf_command.py
- python/pysmurf/client/command/test_sphinx.py
- python/pysmurf/client/debug/smurf_noise.py
- python/pysmurf/client/tune/smurf_tune.py
- python/pysmurf/client/util/smurf_util.py
- python/pysmurf/core/roots/Common.py
- scratch/eyy/noise/noise_vs_fr_freq.py
This PR resolves #467. 
- This implements the new JESD checks.  These features are only usable for pysmurf core code version >4.1.0 (not yet released) and rogue ZIP file versions >0.3.0.
- This adds a `set_check_jesd` to `_set_defaults_cmd`
- changes defaults subbands in `find_freq` to None. This does not change the interface because if None, then it uses the same subbands as before (13, 115)
- changes the default noise bins in `take_noise_psd` to None. If None, loads the same defaults as before, thus no interface change. 
Stolen from this comment (https://github.com/slaclab/pysmurf/issues/467#issuecomment-664688186): 
- `CheckJesd`: it is a command used to trigger a call to the new `AppTop.JesdHealth` method. The command will check if the ZIP file's `AppTop` device contains the new …
> JESD health checks

- python/pysmurf/client/command/smurf_command.py
This PR resolves #487
The `get_configuring_in_progress` and `get_system_configured` should read the PV as string, and return `True` or `False` based on the string the receive. Also, if the PV can not be read they should return `None`.
Then, the `set_defaults_pv` method should check if the value returned by `get_configuring_in_progress` is equal to `False`.
> Fix set_defaults_pv method to determine if the system configuration sequence ended

- python/pysmurf/client/base/smurf_config_properties.py
- python/pysmurf/client/command/smurf_cmd.py
- python/pysmurf/client/command/smurf_command.py
- python/pysmurf/client/command/test_sphinx.py
- python/pysmurf/client/debug/smurf_iv.py
- python/pysmurf/client/debug/smurf_noise.py
- python/pysmurf/client/tune/smurf_tune.py
- python/pysmurf/client/util/smurf_util.py
- scratch/eyy/debug/iv_test.py
- scratch/eyy/test_scripts/profile_band.py
This PR resolves #404, #405, #406.
Fixes some code inconsistency issues: convention for number of samples is now all `nsamp` (different functions had different conventions before such as `n_samp`, `n_samples`), tone power is now all `tone_power` (formerly `drive` or `drive_power`), and function `slow_iv_all` and other relation functions were renamed to `run_iv`, etc.
- `analyze_slow_iv` changed to `analyze_iv`
- `slow_iv_all` changed to `run_iv`
- `set_amplitude_scale_array_currentchans` argument `drive` changed to `tone_power`
- `analyze_slow_iv_from_file` changed to `analyze_iv_from_file`
- `tune_band_serial` argument `drive` changed to `tone_power`
- `set_amplitude_scale_channel` argument `drive` changed to `tone_power`
- `find_freq` argument `drive_power` changed to `tone_power`
- …
> IV functions renamed, now using tone_power and nsamp instead of varying names.

- python/pysmurf/client/debug/smurf_iv.py
This PR resolves #489 and #495 
This passes `bias_line_resistance` from `run_iv` to `analyze_iv_from_file`. 
`run_iv` now has an optional argument for `bias_line_resistance`. If not provided, uses value loaded from the config file.
> Passing bias_line_resistance from run_iv to analyze_iv

- python/pysmurf/client/base/smurf_config.py
This PR resolves https://github.com/slaclab/pysmurf/issues/508.
> Expanded refPhaseDelay config file limits from 4 to 5 bits.

- python/pysmurf/client/util/smurf_util.py
This PR resolves #500.
Changes the `do_plot` optional argument to the standard `make_plot` argument
The optional arguments in `read_adc_data` and `read_dac_data` have changed. `do_plot` is now `make_plot`
Optional argument was `do_plot`
New optional argument `make_plot`
> changing do_plot to make_plot in smurf_util

- python/pysmurf/client/util/smurf_util.py
This PR resolves #529. 
Swaps UC/DC att call at beginning of script.  Due to a typo, script was setting UC as DC and DC as UC.  This fixes.
> Swapping UC/DC att call at beginning of estimate_phase_delay

- include/smurf/core/transmitters/DualDataBuffer.h
- src/smurf/core/transmitters/DualDataBuffer.cpp
~DualDataBuffer is called without properly terminating the tx thread,
causing the main thread to receive a SIGABRT.
I proposed a reduction in the tx loop timeout so that the destructor
doesn't take 10 seconds to finish.
~DualDataBuffer is called without properly terminating the transmitter thread, causing the main thread to receive a SIGABRT.
This patch causes the DualDataBuffer destructor to stop the transmitter thread before calling the thread destructor. It also reduces the timeout in the transmitter loop to 1s from 10s, to prevent the DualDataBuffer destructor from waiting up to 10s before being able to join the thread.
> Fix SIGABRT on DualDataBuffer destruction

- python/pysmurf/client/util/smurf_util.py
This PR resolves #546.
Changes the default argument for `register_file` in `take_stream_data` to False.
> Change register_file default

- python/pysmurf/client/debug/smurf_iv.py
This PR resolves https://github.com/slaclab/pysmurf/issues/512. 
Adds a flag to the [S.run_iv() function](https://github.com/slaclab/pysmurf/blob/491f56f8884ba1e18747c2f64205f6c93e430592/python/pysmurf/client/debug/smurf_iv.py#L37) in order to skip the analysis functions after taking data. Also issues a warning to the log when analysis is skipped. 
- [x ] No
No interface changed. 
N/A
N/A
Main concern is that this branch (iv-analysis-flag) is based on `issue508` branch, which is being used at UCSD because of a known bug in the firmware interacting with our carrier. I'm not sure what the proper way is to merge the changes here to main so that it merges in cleanly, but also how to pull this and update the `issue508` branch we're using correctly so that the new update is included but without …
> Adding flag to skip IV analysis functions after running S.run_iv()

- python/pysmurf/client/base/smurf_control.py
- python/pysmurf/client/command/smurf_command.py
This PR resolves https://github.com/slaclab/pysmurf/issues/554.
Adds two new functions `get_dbg_enable` and `set_dbg_enable` which provide read/write access to the DBG:enable register.  Now explicitly sets DBG:enable=True in setup so that pysmurf can subsequently keep writing to any of the DBG registers (including hitting DAC reset in a subsequent setup, although ideally no one should be running setup twice in the same session).  For details on why this change is needed, see the linked issue and JIRA ticket https://jira.slac.stanford.edu/projects/ESCRYODET/issues/ESCRYODET-765.
> Fix for resetting RF DACs after first setup in latest software versions.

- cfg_files/nist/cmb/experiment_nistcmb_cc02-02_lbOnlyBay0.cfg
- python/pysmurf/client/base/smurf_control.py
- python/pysmurf/client/tune/smurf_tune.py
This PR resolves https://github.com/slaclab/pysmurf/issues/556.
Fixes minor bug in `find_freq`.  See issue for more details.
> Fixes bug that was causing find_freq to crash if not given a start/stop_freq or subband arg.

- .github/workflows/verify-pr-labels.yml
This PR resolves #561 
This PR updates the version of the `verify-pr-label-action` GitHub Action to support PRs from forks.
This version also avoid creating duplicates reviews: if the last review done by this modules was approved/requested changes, and the new state it is the same, the module won't redo the same action.
> Update version of the `verify-pr-label-action` action to support PRs from forks

- .github/workflows/ci-cd.yml
- .github/workflows/label.yml
- .github/workflows/verify-pr-labels.yml
- releaseGen.py
This PR resolves [ESCRYODET-766](https://jira.slac.stanford.edu/browse/ESCRYODET-766).
This PR fixes a remaining issue regarding the migration from Travis to Github Action done in #560. 
The `releaseGen.py` script was still using some Travis-specific environmental variables, which are fixed and made generic in this PR.
This PR also adds the license headers to all the GitHub Action Workflow files, which were missing.
> Github Actions: Fix release generation script, which was still referencing Travis env vars

- docker/server/Dockerfile
This PR resolves [ESCRYODET-683](https://jira.slac.stanford.edu/browse/ESCRYODET-683).
This PR updates Rogue to version [v4.11.6](https://github.com/slaclab/rogue/releases/tag/v4.11.6). This version of Rogue container fixes for float value precision lost though the EPICS interface as describe in [ESCRYODET-683](https://jira.slac.stanford.edu/browse/ESCRYODET-683). 
In the previous version (rogue `v4.11.2`),  if we try to read a register with a float value from python, for example *AMCc/FpgaTopLevel/AppTop/AppCore/SysgenCryo/Base[0]/digitizerFrequencyMHz*, which value is:
```bash
cryo@smurf-srv06:/$ caget smurf_server_s2:AMCc:FpgaTopLevel:AppTop:AppCore:SysgenCryo:Base[0]:digitizerFrequencyMHz
smurf_server_s2:AMCc:FpgaTopLevel:AppTop:AppCore:SysgenCryo:Base[0]:digitizerFrequencyMHz 614.4 …
```
> Update smurf-rogue base image to version R2.8.2

- src/smurf/core/processors/SmurfProcessor.cpp
This PR resolves [ESCRYODET-758](https://jira.slac.stanford.edu/browse/ESCRYODET-758).
This PR fixes a bug related to the mutex locks in the smurf processor code which was causing the server to crash under some conditions. 
As reported by SO here: https://github.com/simonsobs/smurf-issues/issues/10, the issue seen to be caused by resetting the Unwrapper module. I was able to reproduce that issue by:
- Start data streaming (I tested with a 4kHz frame rate), 
- Set a big channel mask size (I tried with 1000 for example).
- Then, on the client side do this loop:
```bash
cryo@smurf-srv06:/$ while :; do caput smurf_server_s2:AMCc:SmurfProcessor:Unwrapper:reset 1 ; sleep 1; done;
``` 
This will eventually make the server to crash as reported bay SO:
```bash
cryo@smurf-srv06:/$ while :; do caput …
```
> Fix mutex lock scopes related to the unwrapper data

- python/pysmurf/core/roots/Common.py
This PR resolves [ESCRYODET-778](https://jira.slac.stanford.edu/browse/ESCRYODET-778).
Make the `find` call look for exactly a `Command` called `JesdHealth`. This avoid having false results. 
This called was finding the `Variable` called `JesdHealthStatus`, added [here](https://github.com/slaclab/amc-carrier-core/pull/321) instead, and breaking the `SmurfApplication/CheckJesd` command.
> Add more restrictions to the find method used to check if `JesdHealth` exists

- docker/client/Dockerfile
This PR resolves #377.
This PR pin the version of the python packages install in the client docker image to the version currently used by our latest release (`v4.1.0`):
```bash
cryo@smurf-srv06:/usr/local/src/pysmurf$ pip3 list | grep -E 'scipy|pandas|PyYAML|seaborn|jupyter|pytest|GitPython|schema'
GitPython (3.1.7)
jsonschema (3.2.0)
jupyter (1.0.0)
jupyter-client (6.1.6)
jupyter-console (6.1.0)
jupyter-core (4.6.3)
pandas (1.1.0)
pytest (6.0.1)
PyYAML (5.3.1)
schema (0.7.1)
scipy (1.5.2)
seaborn (0.10.1)
```
> Pin version of the python packages used in the client docker image

- README.SmurfPacket.md
- include/smurf/core/common/Helpers.h
This PR resolves #505 
Use the UNIX Epoch Time (expressed in nanoseconds) in word 6 of the SMuRF header.
Word 6 in the [SMuRF packet header](https://github.com/slaclab/pysmurf/blob/main/README.SmurfPacket.md).
Word 6 contained the time obtained using [steady_clock](https://en.cppreference.com/w/cpp/chrono/steady_clock), which was a monotonic clock that will never be adjusted (in nanoseconds).
Word 6 now contains the time obtained using [system_clock](https://en.cppreference.com/w/cpp/chrono/system_clock) instead, which is the wall clock time from the system-wide realtime clock, converted to time since Epoch in nanoseconds.
> SMuRF header: Use Unix Epoch time for word 6

- .github/workflows/ci-cd.yml
No issue associated to this PR.
Fix the GitHub token used during the generation of release notes.
> Fix the GitHub token used during the generation of release notes

- .github/workflows/ci-cd.yml
No issue associated to this PR.
The release note generation script needs to be run with a deep checkout, so that is can find the tags.
> Fix GitHub Action job used to generate release notes

- python/pysmurf/client/base/smurf_control.py
- python/pysmurf/core/roots/Common.py
- scratch/eyy/test_scripts/profile_band.py
This PR resolves [ESCRYODET-791](https://jira.slac.stanford.edu/browse/ESCRYODET-791).
This PR fixes a bug in `setup()`, which was continuing with the setup process when `set_defaults_pv` fails. It also reduces the number of number of times the server retries to load defaults to 4, to be equivalent to the 400s timeout the client uses.
This PR also adds a fix to `profile_band.py` test, which should check if `setup()` succeed before continuing with the test.
> Bug fix: During `setup()`, check if `set_defaults_pv` succeeded before continue with setup.

- python/pysmurf/client/debug/smurf_noise.py
This PR resolves #586 .
Changes the name of the `NEI_to_NEP` function to `get_NEI_to_NEP_factor`. The previous name did not make sense. 
`NEI_to_NEP`  function name changed to `get_NEI_to_NEP_factor`
Function was called `NEI_to_NEP`
Now it is called `get_NEI_to_NEP_factor`
> Issue586 - Changing name of NEI_to_NEP to get_NEI_to_NEP_factor

- python/pysmurf/client/command/smurf_command.py
This PR resolves #594 .
the set and get function to emulator periods are strings. Handle that properly.
> Bug in emulator period data type handling

- python/pysmurf/client/command/smurf_command.py
Solves #589 
Catches and retries if `epics.caget` returns None. 
> Adding retry attempt to caget

- python/pysmurf/client/command/smurf_command.py
This PR resolves #598.
This PR makes the [set_default_pv method](https://github.com/slaclab/pysmurf/blob/8899e9e362ad44bd89d20693316002dd81ac53d1/python/pysmurf/client/command/smurf_command.py#L522) behaves the same it was before introducing the changes in #590.
In order to do that, we need to [read the status of the configuration in progress PV](https://github.com/slaclab/pysmurf/blob/8899e9e362ad44bd89d20693316002dd81ac53d1/python/pysmurf/client/command/smurf_command.py#L600), disabling the new `retry_on_fail` and instead catching the `RuntimeError` exceptions and keep retying for `num_retries`. 
I tested this in a system where I modified the `AppTop.Init()` method to always fail (which will be the worse case scenario) and then trying to setup the system from the client. This is what …
> Update `set_default_pv` to handle the new `RuntimeError` exception

- python/pysmurf/client/debug/smurf_noise.py
Issue #603 
Adds a few `register_file` statements to `take_noise_psd` and correctly sets the publisher action.
I'm not exactly sure which branch I should merge this into... I think we have some people running on the main branch, but if find-freq-eta-scan-speedup will be merged soon then I think it's ok.
> Adds a few register_file calls for noise plots

- python/pysmurf/client/base/smurf_control.py
Resolves #600 and https://github.com/simonsobs/smurf-issues/issues/24
Figured out there was an error during setup in this branch that happened because some code was indented once to many times, which caused some of the setup not to be run if `no_dir=True`. This PR de-indents it.
> Fixed no_dir error during setup

- python/pysmurf/core/utilities/_SmurfPublisher.py
This PR resolves #588.
This PR adds the following changes to the [Publisher class](https://github.com/slaclab/pysmurf/blob/main/python/pysmurf/core/utilities/_SmurfPublisher.py) as requested in #588: 
- Metadata publishes will now have `msgtype` set to `metadata`, instead of `general`,
- When publishing metadata, the content of the `data` field will now be key, value pairs, in JSON format, containing the Rogue register path (`path`), the register value (`value`), and the value type (`type`).
I tested this changes, with the [default variable group](https://github.com/slaclab/pysmurf/blob/main/python/pysmurf/core/server_scripts/_VariableGroupExample.py), and modifying the [_backend_null](https://github.com/slaclab/pysmurf/blob/main/python/pysmurf/core/utilities/_SmurfPublisher.py#L122-L123) …
> Smurf Server Publisher modifications

- python/pysmurf/client/debug/smurf_iv.py
This PR resolves https://github.com/slaclab/pysmurf/issues/605 
Adds an output directory keyword (output_dir) to the analyze_iv_from_file so we can dump the analysis results to another location. 
Extra keyword in analyze_iv_from_file
IV analysis outputs could only be saved in the folder structure on the smurf server. Would throw errors if the files had been moved.
Extra keyword in analyze_iv_from_file means you can tell it where to save the results.
> Fixes #605. 

- docker/server/Dockerfile
This PR resolves [ESCRYODET-728](https://jira.slac.stanford.edu/browse/ESCRYODET-728).
This PR updates Rogue to version [v4.11.7](https://github.com/slaclab/rogue/releases/tag/v4.11.7). This version of Rogue contains a fix for the unbound memory usage increase described in [ESCRYODET-728](https://jira.slac.stanford.edu/browse/ESCRYODET-728).
> Update smurf-rogue base image to version R2.8.3

- cfg_files/stanford/experiment_fp31_cc03-02_lbOnlyBay0.cfg
- python/pysmurf/client/base/smurf_config.py
- python/pysmurf/client/base/smurf_config_properties.py
- python/pysmurf/client/base/smurf_control.py
- python/pysmurf/client/command/smurf_command.py
- python/pysmurf/client/command/test_sphinx.py
- python/pysmurf/client/tune/smurf_tune.py
- python/pysmurf/client/util/smurf_util.py
This issue deprecates refPhaseDelay, refPhaseDelayFine and lmsDelay.  We've introduced a new PV bandDelayUs which handles those 3 variables under the hood.  This also improves estimate_phase_delay.
refPhaseDelay, refPhaseDelayFine, and lmsDelay are now deprecated.  These are handled by Rogue in the bandDelayUs PV.
refPhaseDelay, refPhaseDelayFine and lmsDelay in the configuration file
bandDelayUs in the configuration file
> Band delay us

- python/pysmurf/client/command/smurf_command.py
This PR resolves #624.
Creates two hooks for setting and getting the value of the `Disable` field in the `predataEmulator`. One can now set and get the values using the following:
```python
S.set_predata_emulator_disable(True)
value = S.get_predata_emulator_disable()
```
> Add predataEmulator:Disable hooks

- python/pysmurf/client/tune/smurf_tune.py
This PR resolves #630 
Automatically adds the tune file info to rogue every time a tune file is loaded or saved.
Nothing should change for the user
> tuneFilePath not being written

- python/pysmurf/client/util/smurf_util.py
This PR resolves #626 
This PR fixes the payload size issue by replacing the manual determination of the payload size with `S.set_payload_size(0)`. I'm not sure why the other way wasn't working, but we tested at U-chicago, and this does indeed create .dat files with the correct payload size, which drastically decreases the file size when you're not streaming with a full UFM.
> fixes the payload size issue by replacing the manual determination of the payload size

- python/pysmurf/client/util/smurf_util.py
This PR resolves #633.
Adds a `pub.register_file` call once the debug data file closes.
> Registers debug dat file with publisher

- .github/labeler.yml
- .github/workflows/ci-cd.yml
- README.Docker.md
- docker/server/.gitignore
- docker/server/Dockerfile
- docker/server/build.sh
- docker/server/definitions.sh
- docker/server/validate.sh
- releaseGen.py
This PR resolves [ESCRYODET-818](https://jira.slac.stanford.edu/browse/ESCRYODET-818).
This PR brings a simplified version of the **stable** docker image generation from the [pysmurf-stable-docker](https://github.com/slaclab/pysmurf-stable-docker). With this, the **stable** images will be generated from this repository instead. The firmware version is defined in the [definitions.sh file](docker/server/definitions.sh). So now, the stable images will be generated from this repository, when a tag is pushed to it.
On the other hand, now I realize that it not necessary to have a **base** image (the image previously generate from this repository, which didn't contained any firmware file in it). We can simply use the stable image and mount an external FW image in it, when running a …
> Generate stable docker images from this repository

- docker/server/definitions.sh
This PR resolves [ESCRYODET-816](https://jira.slac.stanford.edu/browse/ESCRYODET-816).
This PR updates the FW to version [v1.0.5 (8ccb67e)](https://github.com/slaclab/cryo-det/releases/tag/MicrowaveMuxBpEthGen2_v1.0.5). 
This version of the FW fixes the bug that as only including the first 8 TES bias DAC pairs into the header.
> Update FW to version v1.0.5 (8ccb67e)

- docker/server/definitions.sh
There is not open issue for this PR.
This PR updates the FW to version [v1.0.6 (8ccb67e)](https://github.com/slaclab/cryo-det/releases/tag/MicrowaveMuxBpEthGen2_v1.0.6).
This version of the FW fixes a wrong eta phase shift done in rogue code (see https://github.com/slaclab/pysmurf/pull/643). This change only changes rogue code, so the firmware image (i.e. MCS file) is the same respect to the previous version.
> Update FW to version v1.0.6 (8ccb67e)

- README.config_file.md
- cfg_files/b33/experiment_2xLB_testing_Feb2021.cfg
- cfg_files/b33/experiment_b33_lbOnlyBay0.cfg
- cfg_files/b33/experiment_b33_lbOnlyBay0_flip_hemt_polarity.cfg
- cfg_files/b33/smurf_startup.cfg
- cfg_files/b33/smurf_startup_c03-15.cfg
- cfg_files/template/template.cfg
- python/pysmurf/client/tune/smurf_tune.py
- scratch/eyy/noise/princeton_phi0.py
This PR resolves #649 and #654 .
This adds documentation for config_files. 
This adds an optional variable that flips the phase before taking a derivative in `find_freq`.
> Adding config_file documentation and phase flipping optional variable in find_freq

- python/pysmurf/client/util/smurf_util.py
This PR should greatly speed up the creation of frequency mask by changing the required number of epics get requests from  being proportional to the number of channels to being proportional to the number of bands. This use to take ~minutes for a full UFM.  Resolves #662 .
This has not been tested yet, so I'll test when we have a cold system available (or someone else on SO can test before then) and then we can switch this from a draft to a full PR when it works.
The current implementation of this function makes a number of epics requests for each channel, which takes a very long time when there are a lot of channels. The new version uses the centerFrequencyArray registers etc. to get info for all channels in a given band at once, which should speed it up a lot.
> speed up make_freq_mask

- python/pysmurf/client/base/smurf_control.py
Resolves #664. 
Adds the `data_path_id` to the smurf_control args, which allows one to set a unique id in the data path to avoid collisions.
> Adds data_path_id to SmurfControl Args

- include/smurf/core/common/SmurfPacket.h
- src/smurf/core/common/SmurfPacket.cpp
This PR resolves #676.
Adds a getAllData function to the SmurfPacket class that returns an array containing all detector data. This eliminates repeated function calls to the getData function.
Tested with the SO smurf-streamer, and greatly improves data processing speeds at high channel counts.
> Adds getAllData method

- docker/server/Dockerfile
- docker/server/definitions.sh
No issue.
This updates pysmurf to use the latest Rogue version v4.11.10 and cryo-det firmware version v1.1.0. Ruckman compiled the .mcs.gz file, and I assume attached it manually to the cryo-det release. I updated the smurf-rogue-docker version to R2.8.8 which compiled Rogue. The firmware file has not been thoroughly tested.
NA
NA
NA
> Update cryo-det firmware to v1.1.0 and Rogue to v4.11.10

- python/pysmurf/client/command/smurf_command.py
Closes #688
set_enable_ramp times out when writing to its PV. It's not used when turning on the flux ramp. I couldn't find it in pysmurf, sodetlib, or cryo-det. However EnableRampTrigger is used. If EnableRamp isn't actually used anywhere and is not needed for backwards compatibility, we can delete this.
https://github.com/slaclab/pysmurf/blob/41e41c9c568aecd7e350ff2f050be58498c56af9/python/pysmurf/client/command/smurf_command.py#L4461
https://github.com/slaclab/pysmurf/blob/41e41c9c568aecd7e350ff2f050be58498c56af9/python/pysmurf/client/tune/smurf_tune.py#L3200
https://confluence.slac.stanford.edu/display/SMuRF/RTM+firmware?preview=/232089354/233309457/Cryo_RTM_setup_note_v2.pdf
> Remove set_enable_ramp

- docker/server/Dockerfile
- docker/server/definitions.sh
No issue
Update pysmurf to Rogue v4.11.10 and cryo-det v1.1.0. Major changes is the cryo-det U_timing messages were increased in size, the version number of cryo-det was incremented, and minor changes to Rogue.
NA
NA
NA
> Update cryo-det firmware to v1.1.0 and Rogue to v4.11.10 (#682)

- .github/workflows/test-or-deploy.yml
- docker/server/validate.sh
Problem
The pysmurf repository itself needs access to the private cryo-det
repo in order to run tests and generate release images. For some
reason the current token broke.
Solution
The simple thing to do is make some access token in cryo-det and then
put that in pysmurf's private environment keys. But strangely this
isn't possible. Instead Github requires users make "Personal Access
Tokens" which are owned by specific users, and Github suggests we make
another machine user entirely. I don't want to juggle two Github
accounts, so just put it in my account for now.
> Fix automated access to cryo-det

- python/pysmurf/client/command/cryo_card.py
Problem
Pysmurf should be able to control the flux ramp coupling mode for the C02 and C04, either DC mode or AC mode. To do this, the C02 controls two relays, K1 and K2, while the C04 uses just one relay named K2.
Solution
The easiest solution is to set bit 16 on address 0x2 on the PIC. This controls both relays on the C02, and just the K2 on the C04, which is very convenient. To read back the AC/DC status, just read back the same bit. This deprecates the usage of address 0x08 on the C02 firmware. If we still want to use that address, the code gets more complicated. 
Functions added:
- cryo_card.py
- get_relay_bit
- set_relay_bit
Functions modified:
- cryo_card.py
- read_ac_dc_relay_status
Problems
- Some parts of pysmurf expect a value of 3 instead of 1 from read_ac_dc_relay_status. 3 …
> Control flux ramp AC/DC coupling on the C02 and C04 Cryocard

- docker/server/definitions.sh
Add config for SMuRF so the automatic hardware detection can use one C02 LB on the right (0), C02 HB on the left (1). Used for RF Thermal Testing.
> Adding bay 0 LB + bay 1 HB C02 defaults.yml

- include/smurf/core/common/SmurfHeader.h
- include/smurf/core/processors/SmurfProcessor.h
- python/pysmurf/client/command/smurf_command.py
- python/pysmurf/client/debug/smurf_noise.py
- python/pysmurf/client/util/smurf_util.py
- python/pysmurf/core/devices/_SmurfProcessor.py
- src/smurf/core/common/SmurfHeader.cpp
- src/smurf/core/emulators/StreamDataSource.cpp
- src/smurf/core/processors/SmurfProcessor.cpp
Data for SMuRF is maximally available at the flux ramp frequency. Previously, SMuRF could only use its internal "downsampler counter" where it ignores some of the incoming data until the counter is reached. This code change adds the ability for SMuRF to look at external timing bits from the SMuRF timing hardware to decide when to save data. I note that there are two places where SMuRF data is downsampled: at the firmware layer, and here at the software layer. The firmware layer does averaging of its data, but here the data is not averaged. The software downsampling simply drops the unused frames.
> Downsample from either the internal downsampler counter, or external bits from timing system

- python/pysmurf/client/command/cryo_card.py
- python/pysmurf/client/command/smurf_command.py
- python/pysmurf/client/tune/smurf_tune.py
- python/pysmurf/client/util/smurf_util.py
- scratch/cyu/cryochannel.py
- scratch/cyu/etascan.py
- scratch/shawn/thermal_test.py
This PR explicitly enforces `use_monitor=False` as the default in all pysmurf `caget` calls in pysmurf so we're compatible with newer versions of pyepics (e.g. 3.5.1+) where the default `use_monitor=False` was changed to `use_monitor=True` which at a minimum breaks pysmurf's ability to poll cryostat card registers (and who knows what else).  For more details see the github issue https://github.com/slaclab/pysmurf/issues/725.  This PR is part of work to try and upgrade some of the software (like Ubuntu and pyepics) in the pysmurf docker because some of the currently used versions are soon to be EOL'd.
https://github.com/slaclab/pysmurf/issues/725
Booted a SMuRF system up using `jackhammer` into @jlashner's experimental dockers with newer software (including version 3.5.1 of pyepics) but …
> pyepics use_monitor=False override for all caget calls for forwards pyepics compatibility

- docker/client/Dockerfile
Automated checks were failing for PRs due to two problems; 1) some of the required status checks seem to no longer be defined and 2) Client Tests were failing because pip3 failing to install jupyter. 
1) was fixed by changing repo settings.  2) by adding command to client Dockerfile to update pip3 before installing jupyter.
https://github.com/slaclab/pysmurf/issues/727 but also [ESCRYODET-889](https://jira.slac.stanford.edu/browse/ESCRYODET-889)
> Fixes so PRs will pass automated checks again.

- cfg_files/slac/experiment_rflab_onlyBay0.cfg
- cfg_files/slac/experiment_rflab_thermal_testing_201907.cfg
- cfg_files/slac/experiment_so_westpak_6carrier_14day_test.cfg
- cfg_files/slac/rflab_smurf_startup.cfg
- cfg_files/slac/rflab_smurf_startup_stephen_test.cfg
- cfg_files/slac/smurf_startup_6carrier.cfg
- cfg_files/slac/smurf_startup_dan.cfg
- cfg_files/slac/smurf_startup_low_power_test.cfg
- cfg_files/slac/smurf_startup_mitch.cfg
- cfg_files/slac/smurf_startup_so_westpak_6carrier_14day_test.cfg
- cfg_files/slac/smurf_startup_thermal_test.cfg
- cfg_files/slac/srv11.cfg
- python/pysmurf/client/command/cryo_card.py
- python/pysmurf/client/command/smurf_command.py
- python/pysmurf/client/debug/smurf_noise.py
- python/pysmurf/client/util/smurf_util.py
This PR improves docstrings and does some cleanup for [ESCRYODET-472](https://jira.slac.stanford.edu/browse/ESCRYODET-472), which is the SLAC JIRA issue for adding external triggering to the downsampler.  Also adds a convenience function `get_timing_fiber_status` for confirming a slot 2 carrier receiving timing over fiber and distributing it over the backplane is receiving timing data and has its crossbar configured properly, and reverts to our prior convention of using `downsample` instead of `downsampler` in the names of all functions related to downsampling. 
Backwards compatible changes in this PR include:
* Improved or added missing docstrings for the `write_ps_en`, `get_cryo_card_temp`, `get_crossbar_output_config`, `get_downsample_factor`, `get_downsampler_external_bitmask`, …
> Add commands for external timing functionality

- python/pysmurf/client/base/smurf_control.py
- python/pysmurf/client/tune/smurf_tune.py
Adds `data_path_id` to the tune_dir to make sure different slots have unique paths.
We just noticed tune data from different slots are all being saved to the same directory. This can be problematic when operating multiple slots simultaneously, as it's possible that different slots have the same timestamp associated with the tune, in which case the tune-files will be overwritten. Additionally, attempting to pull the latest tune_file using `S.load_tune()` will pull the most recent one out of all slots. 
We added `data_path_id` before to make sure `output` and `plot` directories don't conflict across slots, so it makes sense to extend this to the tune directory as well.
None yet but it seems straight-forward
None
> Adds data_path_id to the tune_dir

- .github/workflows/test-or-deploy.yml
- README.md
- setup.py
This adds all the dependencies listed in the `requirements.txt` file to the `setup.py` file, allowing a one-step installation via pip. This is per the [python packaging guidelines](https://packaging.python.org/en/latest/guides/distributing-packages-using-setuptools/#install-requires).
On my end in packaging work I'm doing for SO I want to be able to add pysmurf as a dependency like:
```
pysmurf @ git+https://github.com/slaclab/pysmurf.git@main
```
and get any dependencies required by pysmurf automatically. This change would enable that.
Naturally the question arises of whether you maintain the dependency list twice both in `setup.py` and in `requirements.txt`. Those files serve two different purposes (see the [python packaging docs](https://packaging.python.org/en/latest/discussions/instal …
> Add dependencies to setup.py as install_requires

- cfg_files/lab1/experiment_lab1_2xLB_c04cc_extref.cfg
- python/pysmurf/client/base/smurf_control.py
- python/pysmurf/client/command/smurf_command.py
- python/pysmurf/client/util/smurf_util.py
This PR adds new functions to utils named `get_timing_mode` and `set_timing_mode` which allow you to check what timing mode a carrier is configured in (supported modes are our typical "ext_ref", "backplane", and "fiber" modes).   This closes out issue pysmurf github https://github.com/slaclab/pysmurf/issues/734.  No interface changes.  Some implementation details:
* Stripped all the timing stuff out of `setup` ; it now just uses the new `set_timing_mode` function.
* I tried to make the functions smart enough to catch some common errors like asking for an external timing mode (currently either "backplane" or "fiber") but no external timing data is coming in or e.g. trying to configure a slot 2 carrier for "backplane" timing or a slot 3-7 carrier for "fiber" timing.
* I added a lot more …
> New functions to get/set timing modes

- python/pysmurf/client/base/smurf_control.py
- python/pysmurf/client/command/smurf_command.py
- python/pysmurf/client/tune/smurf_tune.py
- scratch/shawn/logtimingpackets.py
This PR implements a fix for [issue737](https://github.com/slaclab/pysmurf/issues/737) and [sodetlib issue300](https://github.com/simonsobs/sodetlib/issues/300) where users were seeing duplicate data for unassigned channels stored in the `freq_resp` dictionary populated by `setup_notches`.  The issue was that the method `setup_notches` uses to sweep channels can only run on assigned channels.  That method is used because it is faster than sweeping every resonator serially, but a bug was causing it to populate the resp data of the unassigned channels, which it wasn't sweeping, with data from other channels.  Here's where the bug was:
https://github.com/slaclab/pysmurf/blob/eb9f7be55e6e49446fc72621e21e85596f5962a6/python/pysmurf/client/tune/smurf_tune.py#L3974
Unassigned channels get …
> Bug fix for setup_notches for unassigned channels, add SystemConfigured check.

- python/pysmurf/client/util/smurf_util.py
In recent PR [#738](https://github.com/slaclab/pysmurf/pull/738) I added new `set_timing_mode` and `get_timing_mode` functions.  As I wrote it, `set_timing_mode` does not allow a non-slot 2 system to be configured for fiber timing, but that's too restrictive.  This PR fixes that and resolves [issue743](https://github.com/slaclab/pysmurf/issues/743).
> Allow configuring systems in slots 3-7 for fiber timing.

- python/pysmurf/client/tune/smurf_tune.py
Passes `grad_kernel_width` keyword to `find_peak` in `smurf_tune` from `find_all_peak`.  `grad_kernel_width` was an allowed keyword of the `find_all_peak` function, but it wasn't actually being passed on to `find_peak`!
> Include grad_kernel_width kwarg in find_peak call

- python/pysmurf/client/tune/smurf_tune.py
- scratch/shawn/scripts/shawnhammer.sh
No longer trying to plot setup_notches data for unassigned channels, which causes the `plot_tune_summary` function to crash.  Tested both with the `setup_notches` routine's `scan_unassigned` keyword True and False.  Fixes issue #757.  No interface changes.
[20230317_issue757.ipynb.gz](https://github.com/slaclab/pysmurf/files/11005950/20230317_issue757.ipynb.gz)
> Fix bug causing plot_tune_summary to crash if eta_scan=True and there are any unassigned channels in freq_resp dict.

- .github/workflows/test-or-deploy.yml
- docker/client/Dockerfile
- docker/server/Dockerfile
Upgrading a lot of supporting software including:
- python 3.6.9 -> 3.8.10
- Ubuntu 18.04 -> 22.04 (including in smurf-base-docker and smurf-rogue-docker).  To do this, upgrading from smurf-base-docker release R1.1.1 to R2.0.0 and smurf-rogue-docker release R2.8.8 to R2.9.0.
- Upgrading smurf-pcie version checked out by server Dockerfile from v2.0.0 to latest v2.3.0.
- Updated python version sphinx docs gets built against from 3.6.9->3.8.10.
Closes issue https://github.com/slaclab/pysmurf/issues/764.  The Ubuntu 18.04->20.04 upgrade is needed because GitHub is no longer supporting version 18.04.
Still needs to be tested on hardware.
No interface changes, but lots of low level software versions have changed, so should be prepared for unexpected behavior.
> Upgrade Ubuntu in the base and rogue dockers from version 18.04 to 20.04.

- docker/server/definitions.sh
Also addresses pysmurf issue https://github.com/slaclab/pysmurf/issues/753.  Fixes subtle issue with Rogue zip file defaults which was causing the RTM precision slow DACs to rail fullscale negative for ~1 sec on pysmurf `setup`.  SO users report seeing significant heating in cryostats during setup, and this is the likely culprit.
[ESCRYODET-924](https://jira.slac.stanford.edu/browse/ESCRYODET-924)
Fix tested on the bench (see [ESCRYODET-924](https://jira.slac.stanford.edu/browse/ESCRYODET-924) for details).  Should retest in full release.
No interface changes.
> Rogue defaults fix for RTM precision slow DAC configuration to prevent railing fullscale negative for ~1 sec on configure.

- cfg_files/rflab/experiment_rflab_2xLB_backplane.cfg
- cfg_files/rflab/experiment_rflab_2xLB_extref.cfg
- cfg_files/rflab/experiment_rflab_2xLB_fiber.cfg
- python/pysmurf/client/command/smurf_command.py
- python/pysmurf/client/util/smurf_util.py
- scratch/shawn/logtimingpackets.py
- scratch/shawn/meas_rf_phase.py
Adds new `set_max_file_size` and `get_max_file_size` to restore support for splitting streamed data over multiple files of a fixed size.  If set to zero, streams to the same file indefinitely.  Otherwise if nonzero, streams to the set value in number of bytes.  E.g. `set_max_file_size(2000000)` will set the file partition size to 20MB per file.  Files are split by appending an incrementing integer on the end of the usual ctime taggedfile name ; e.g. .1, .2, .3, etc..  Addresses issue #759.
Also removes datafile glob in `read_stream_data` and added logic to find the mask for rolling data files (which only gets written to disk once for MaxFileSize!=0).
> Add set/get for MaxFileSize to allow splitting long streaming acquisitions over multiple files based on file size.

- docker/server/Dockerfile
Reverting smurf-pcie version to from v2.3.0 back to v2.0.0 in hopes of fixing issue https://github.com/slaclab/pysmurf/issues/766.
> Reverting smurf-pcie version to from v2.3.0 back to v2.0.0.

- docker/server/Dockerfile
Update to new smurf-rogue-docker release R2.9.1 which fixes server gui crash.  R2.9.1 uses an earlier version of PyDM which doesn't cause the crash.  Closes issue #768.
No interface changes.
> Update to new smurf-rogue-docker release R2.9.1 which fixes server gui crash.

- python/pysmurf/client/util/smurf_util.py
After upgrading Ubuntu in the SMuRF dockers from 18.04->20.04, `numpy.int` is deprecated in the default version of numpy in the updated dockers.  This happened in numpy version 1.20.0 ; https://numpy.org/doc/stable/release/1.20.0-notes.html#using-the-aliases-of-builtin-types-like-np-int-is-deprecated.  But it turns out `numpy.int` was just an alias for the builtin `int` type.  Fixing by just using `int` instead (but typecasting to `numpy.int64` to match the docstring's return value).  Tested on a system in loopback by reading back adc data (via the `read_adc_data` function).  Closes https://github.com/slaclab/pysmurf/issues/770.  No interface changes.
> Fixing deprecated numpy.int call after numpy upgrade.

- docker/server/Dockerfile
Trying to fix issue https://github.com/slaclab/pysmurf/issues/772 ; some critical routines like `read_adc_data` and `find_freqs` are not returning good data, suspect due to newer PyDM version used in recently upgraded dockers (post SMuRF software version 7.2.0).  SO dockers use same docker setup (so very similar software versions) and their last build didn't have this issue and used PyDM v1.17.0, so trying that by building a SMuRF release on https://github.com/slaclab/smurf-rogue-docker/releases/tag/R2.9.2 which requires PyDM v1.17.0.
> Drops pydm from v1.18.2 to 1.17.0.

- docker/server/Dockerfile
Core code lost the ability to ascertain the SMuRF software version in releases > v7.2.0.  Probably due to git upgrade in the dockers.  Trying adding a line to the server Dockerfile to fix.
Details in https://github.com/slaclab/pysmurf/issues/773.
> Attempted fix for `pysmurf.__version__`.

- docker/server/Dockerfile
Tweak on https://github.com/slaclab/pysmurf/pull/776 which should work (needed to have run as the cryo user, not as the root user).  Tested in a rudimentary docker where I just checked out pysmurf.  Closes https://github.com/slaclab/pysmurf/issues/773.
> Issue773 try2

- python/pysmurf/client/util/smurf_util.py
Plots produced by `read_dac_data` have ADC in y-label of FFT ; this PR corrects that to read DAC instead.  This PR has no corresponding issue - just a quick fix.
> ADC->DAC in y-axis label of `read_dac_data` plots.

- python/pysmurf/client/util/smurf_util.py
Fix for overlapping title in plots produced by `check_full_band_resp`.  This PR has no corresponding issue - just a quick fix.
> Fix for overlapping title in plots produced by `check_full_band_resp`

- python/pysmurf/client/command/smurf_command.py
- scratch/shawn/check_crate_thermal_sensors.py
Exposes `epics.PV.get` timeout option to `smurf_command._caget` and sets default to 5 sec.  When we moved to PV caching in pysmurf release [v7.2.0](https://github.com/slaclab/pysmurf/releases/tag/v7.2.0), we switched to querying registers using the `epics.PV.get` function which has a default 2 sec timeout instead of the `epics.caget` function we had been using previously which has a longer default 5 sec timeout.  On some systems this resulted in timeouts.  Resolves issue #780.  Tested like this:
```
%timeit -r1 -n1 S._caget('xxx')
[ 2023-06-16 22:41:07 ]  Command failed: xxx
[ 2023-06-16 22:41:07 ]  Retry attempt 1 of 5
[ 2023-06-16 22:41:12 ]  Retry attempt 2 of 5
[ 2023-06-16 22:41:17 ]  Retry attempt 3 of 5
[ 2023-06-16 22:41:22 ]  Retry attempt 4 of 5
[ 2023-06-16 22:41:27 ]  Retry …
```
> Adding timeout as an option to the underlying `epics.PV.get call` with 5 sec as default

- .github/workflows/test-or-deploy.yml
- docker/server/definitions.sh
- docker/server/scripts/server_common.sh
- docker/server/validate.sh
Extends hardware detection to include single-AMC TKID systems (with the TKID AMC in bay 0).  To work, the TKID AMC baseboard must have its FRU correctly programmed to reflect that it is a TKID AMC - this requires that the loading segment of its S/N be A03.  Many (maybe all) of the TKID AMCs were recycled from LB (=A01) and HB (=A02) AMCs, so using this new feature may require reprogramming your TKID AMC's FRU.  Instructions for how to do that are here - https://confluence.slac.stanford.edu/display/CMBS4SLAC/TKID+SMuRF+hardware#TKIDSMuRFhardware-TKIDAMCbasecardfrureprogramming.
This also bumps the smurf_cfg release from v2.0.0->v2.1.0 to pickup updated TKID defaults files.  See https://github.com/slaclab/smurf_cfg/releases/tag/v2.1.0 for more details.
There is no issue associated with this …
> Enable hardware detection for systems running a single TKID AMC in bay 0

- docker/server/Dockerfile
This updates the Rogue version to 4.11.11. This new version of Rogue is linked to the latest version of the KCU1500 driver which is not backwards compatible with Rogue 4.11.10. This new aes-stream-driver supports the latest kernel version of is aligned to the updated firmware distribution for the KCU1500 which fixes the receive crc errors.
> Update rogue version to 4.11.11

- docker/server/Dockerfile
This updates the smurf-pcie version to [v3.0.2](https://github.com/slaclab/smurf-pcie/releases/tag/v3.0.2). This new version This back-applies all of the fixes that existed in the smurf-pcie-docker repo and adds EPICs scripts.
> Upgrade smurf-pcie to v3.0.2.

- docker/server/Dockerfile
This changes the PCIE repo back to a slightly modified version of the original repo used by pysmurf. 
Additional changes include using the https path for the submodules.
Changes to PCIE from the previously used repo can be seen here:
https://github.com/slaclab/smurf-pcie/compare/c63d76346356ee17f7af3891c6a5c0b35c77818b...v2.0.0.1
> Change PCIE Repo to known stable version

- python/pysmurf/client/base/smurf_config.py
- python/pysmurf/client/base/smurf_control.py
Addresses issue https://github.com/slaclab/pysmurf/issues/789, which fixes SO issue https://github.com/simonsobs/sodetlib/discussions/423.  This is an edge case that only effects users who don't provide `lmsDelay` in their pysmurf cfg files and don't run the `smurf_util.estimate_phase_delay` routine, which triggers the low level rogue setBandDelay routine (https://github.com/slaclab/cryo-det/blob/797fa80aa0e43bc4c0939921702a053f3f69ed2b/firmware/python/CryoDet/DspCoreLib/CryoDetCmbHcd/_CryoFreqBand.py#L661) which properly sets the lmsDelay register.
The lmsDelay register matches the system latency for the tracking feedback.  The readout has both actuator and sensor delay, so this delay is needed to compensate the feedback.  Actuator delay is the delay from DSP -> synthesis filter bank -> …
> Remove errant factor of 4 in `smurf_control.setup()` call to `set_lms_delay()`

- python/pysmurf/client/base/base_class.py
- python/pysmurf/client/command/cryo_card.py
Addresses issue #792 
N/A
It's a simple enough fix that that testing didn't seem necessary.
N/A
N/A
N/A
> fix(client.command.cryo_card): Catch EPICS timeout on read and retry.

- python/pysmurf/client/base/smurf_config.py
- python/pysmurf/core/server_scripts/Common.py
Add a log handler with timestamps to capture the output of the rogue (and other) logs.
This works, but rogue is extremely verbose at the `INFO` level. It might be useful to set a more relaxed level for just the `cryo-det` modules.
ESCRYODET-
[Indicate here what is the interface that changed, preferably with a link to the code where the interface is defined]
> feat(core.server_scripts.Common): Set log level and format.

- docker/server/definitions.sh
- python/pysmurf/client/base/smurf_config.py
New firmware includes a fix to the stream FIFO that can cause it to lock up if a very large frame is encountered.
> docker.server: Update carrier FW tag.

- python/pysmurf/client/base/smurf_control.py
Fix for https://github.com/slaclab/pysmurf/issues/801.  Due to recent PR https://github.com/slaclab/pysmurf/pull/794 if no cryostat card is connected to a system, it stalls near the end of setup().  This is actually good behavior, but causes stalls during `setup()` on systems with no cryostat card (=cc) connected.  Systems often don't have ccs connected at SLAC during bring-up testing, this PR just adds a try/except to the CC-related calls in `setup()` to get around this bug.
Ran with change on system with no cryostat card connected to confirm it solves the issue.
N/a
> Add try/except to cryostat card (=cc) commanding in `setup()` so systems running without ccs don't stall in `setup()`.

- python/pysmurf/client/util/smurf_util.py
Closes https://github.com/slaclab/pysmurf/issues/807.
N/A.
> Removes hardcode limiting RF I/Q data to unfiltered 2.4 MHz data only.

- .github/workflows/test-or-deploy.yml
- docker/client/Dockerfile
- docker/server/Dockerfile
No longer able to release pysmurf because dockers built on Ubuntu 20.04 have been sunsetted.  This bumps the smurf-base-docker revision to https://github.com/slaclab/smurf-base-docker/releases/tag/R3.0.2 and the smurf-rogue docker to revision https://github.com/slaclab/smurf-rogue-docker/releases/tag/R2.10.1.  These new releases are just rebuilds of these dockers based on Ubuntu 22.04 instead of 20.04.
> Upgrades to newer base and rogue dockers built on Ubuntu 22.04.
