slaclab/pysmurf

- scratch/eyy/noise/remove_svd_example.py
- tune/smurf_tune.py
Fix for this request: https://github.com/slaclab/pysmurf/issues/22
Not including channel number because we haven't assigned channels yet. However I added resonator number.
> Eta plot fix

- command/smurf_command.py
- tune/smurf_tune.py
Added a utility that takes Shawn's script and generalizes it to make a fake dictionary for any bands.
> Fake res dict

- tune/smurf_tune.py
apparently a wild line break appeared somewhere in my merging attempts
> fixed a broken line that was causing errors

- command/smurf_command.py
- util/smurf_util.py
- util/tools.py
> Working example of yml file use

- base/smurf_control.py
- scratch/shawn/scripts/init_rflab.py
- scratch/shawn/scripts/shawnhammerfunctions.sh
- util/smurf_util.py
Fixes the 3x minor bugs in release [v3.1.0](https://github.com/slaclab/pysmurf/releases/tag/v3.1.0) documented in issue https://github.com/slaclab/pysmurf/issues/72.
> Resolves pysmurf issue 72

- pysmurf/tune/smurf_tune.py
> Fix Publisher typos in smurf_tune.

- pysmurf/util/smurf_util.py
This resolves https://github.com/slaclab/pysmurf/issues/119
> Adding function to get downsample filter parameters

- python/pysmurf/client/util/smurf_util.py
- python/pysmurf/core/devices/_SmurfProcessor.py
- python/pysmurf/core/roots/CmbEth.py
- python/pysmurf/core/roots/CmbPcie.py
- python/pysmurf/core/roots/DevBoardEth.py
- python/pysmurf/core/roots/DevBoardPcie.py
https://jira.slac.stanford.edu/browse/ESCRYODET-424
> Add metadata to the data file 

- python/pysmurf/client/util/smurf_util.py
https://jira.slac.stanford.edu/browse/ESCRYODET-427
> Extract the information from the smurf header in the client code that read the data file

- cfg_files/stanford/experiment_fp30_cc02-03_lbOnlyBay0.cfg
- python/pysmurf/client/command/smurf_command.py
- python/pysmurf/client/util/smurf_util.py
Adding get_filter_params to pre-release for rogue 4. This is changed from rogue 3.
> Pre release filter param

- docker/client/Dockerfile
https://jira.slac.stanford.edu/browse/ESCRYODET-428
> Add pytest to the client docker 

- python/pysmurf/client/base/base_class.py
- python/pysmurf/client/command/smurf_command.py
- python/pysmurf/client/util/smurf_util.py
https://jira.slac.stanford.edu/browse/ESCRYODET-425
> Process data files with dynamic data frame sizes. 

- include/smurf/core/processors/SmurfProcessor.h
- src/smurf/core/processors/SmurfProcessor.cpp
https://jira.slac.stanford.edu/browse/ESCRYODET-432
> Update the number of channel if the payload size is lower than the number of mask values

- include/smurf/core/processors/SmurfProcessor.h
- python/pysmurf/core/devices/_SmurfProcessor.py
- src/smurf/core/processors/SmurfProcessor.cpp
https://jira.slac.stanford.edu/browse/ESCRYODET-433
> Add command to reset the unwrapper and filter from pyrogue

- python/pysmurf/core/roots/CmbEth.py
- python/pysmurf/core/roots/CmbPcie.py
- python/pysmurf/core/roots/Common.py
- python/pysmurf/core/roots/DevBoardEth.py
- python/pysmurf/core/roots/DevBoardPcie.py
- python/pysmurf/core/roots/EmulationRoot.py
- server_scripts/cmb_eth.py
- server_scripts/cmb_pcie.py
- server_scripts/common.py
- server_scripts/dev_board_eth.py
- server_scripts/dev_board_pcie.py
- server_scripts/emulate.py
This PR moves the common root code into a root sub-class.
In the common root I adjusted the Tes bias var update chain.
In the server scripts directory I moved common code to a separate library.
> Create common root sub-class & common server script library

- python/pysmurf/client/util/smurf_util.py
Replace "is" with "==" in the channel compare.
I am not fully convinced this is the source of the problem.
> Fix channel compare in data reader

- python/pysmurf/core/roots/Common.py
Check if the EPICS server is requested by the user before starting it. Also, check if the other features related to it (stream data to PV, and PV dump file) were requested as well.
https://jira.slac.stanford.edu/browse/ESCRYODET-441
> Check if the EPICS features were requested before adding them

- .travis.yml
- docker/server/Dockerfile
Update smurf-rogue base image to version R2.3.0
https://jira.slac.stanford.edu/browse/ESCRYODET-446
> Update Rogue to version v4.5.1

- pysmurf/util/smurf_util.py
Fixes issue https://github.com/slaclab/pysmurf/issues/161.
> Fix for issue 161.

- pysmurf/debug/smurf_noise.py
- pysmurf/tune/smurf_tune.py
Fixes for minor issues https://github.com/slaclab/pysmurf/issues/158 and https://github.com/slaclab/pysmurf/issues/154.
> Fixes for pysmurf issues 154 and 158

- include/smurf/core/common/SmurfHeader.h
- include/smurf/core/conventers/Header2Smurf.h
- python/pysmurf/core/devices/_SmurfProcessor.py
- server_scripts/dev_board_eth.py
- server_scripts/dev_board_pcie.py
- src/smurf/core/common/SmurfHeader.cpp
- src/smurf/core/common/TesBiasArray.cpp
- src/smurf/core/conventers/Header2Smurf.cpp
https://jira.slac.stanford.edu/browse/ESCRYODET-456
> Include the TesBias values into the SMuRF header

- pysmurf/tune/smurf_tune.py
> Fixing eta_width hardcode in plot_tune_summary

- src/smurf/core/common/SmurfHeader.cpp
https://jira.slac.stanford.edu/browse/ESCRYODET-465
> Fix bug in SmurfHeader: bad calls to setWordBit

- README.Docker.md
- docker/server/scripts/start_server.sh
https://jira.slac.stanford.edu/browse/ESCRYODET-443
> Support using a firmware repository local checkout

- src/smurf/core/emulators/StreamDataEmulator.cpp
https://jira.slac.stanford.edu/browse/ESCRYODET-476
> Bug fix: emulator was using wrong number of channel variable 

- python/pysmurf/core/devices/_SmurfProcessor.py
so that the PV is created with that capacity
https://jira.slac.stanford.edu/browse/ESCRYODET-490
> Set the Mask list initial size = 4096

- python/pysmurf/core/devices/_PcieCard.py
https://jira.slac.stanford.edu/browse/ESCRYODET-501
> Disable the ZMQ server for the PCIe card root

- src/smurf/core/common/SmurfPacket.cpp
the smurf packet.
https://jira.slac.stanford.edu/browse/ESCRYODET-512
> Bug fix: fix bad type of casting while extracting the data from

- src/smurf/core/processors/SmurfProcessor.cpp
and payloadSize was not implemented correctly. 
https://jira.slac.stanford.edu/browse/ESCRYODET-513
> Bug fix: inputData size was not being resize

- README.DataEmulator.md
- README.SmurfProcessor.md
- include/smurf/core/emulators/StreamDataEmulator.h
- python/pysmurf/core/devices/_SmurfProcessor.py
- python/pysmurf/core/emulators/_StreamDataEmulator.py
- src/smurf/core/emulators/StreamDataEmulator.cpp
https://jira.slac.stanford.edu/browse/ESCRYODET-515
> Test modes: add frame drop mode, and increase the amplitude range

- README.DataEmulator.md
- README.SmurfProcessor.md
- include/smurf/core/emulators/StreamDataEmulator.h
- python/pysmurf/core/devices/_SmurfProcessor.py
- python/pysmurf/core/emulators/_StreamDataEmulatorI16.py
- python/pysmurf/core/emulators/_StreamDataEmulatorI32.py
- python/pysmurf/core/emulators/__init__.py
- src/smurf/core/emulators/StreamDataEmulator.cpp
- src/smurf/core/emulators/module.cpp
https://jira.slac.stanford.edu/browse/ESCRYODET-516
> Add test modes after the smurf processor

- pysmurf/util/smurf_util.py
Frequency is already in MHz, no need to scaled by 1e-6
> Fix read_adc/read_dac frequency scaling

- include/smurf/core/conventers/Header2Smurf.h
- include/smurf/core/counters/FrameStatistics.h
- include/smurf/core/processors/SmurfProcessor.h
- python/pysmurf/core/counters/_FrameStatistics.py
- src/smurf/core/common/SmurfHeader.cpp
- src/smurf/core/common/SmurfPacket.cpp
- src/smurf/core/conventers/Header2Smurf.cpp
- src/smurf/core/counters/FrameStatistics.cpp
- src/smurf/core/emulators/StreamDataEmulator.cpp
- src/smurf/core/processors/SmurfProcessor.cpp
https://jira.slac.stanford.edu/browse/ESCRYODET-524
> Do sanity checks on the incoming frame

- README.SmurfProcessor.md
- include/smurf/core/processors/SmurfProcessor.h
- src/smurf/core/common/SmurfPacket.cpp
- src/smurf/core/conventers/Header2Smurf.cpp
- src/smurf/core/counters/FrameStatistics.cpp
- src/smurf/core/emulators/StreamDataEmulator.cpp
- src/smurf/core/processors/SmurfProcessor.cpp
https://jira.slac.stanford.edu/browse/ESCRYODET-528
> Bug fixes and cleanup in the SmurfProcessor

- python/pysmurf/core/server_scripts/Common.py
config directory in under python, and the TopRoguePackage, which is
CryoDet in our case.
https://jira.slac.stanford.edu/browse/ESCRYODET-562
> The ZIP file contains the python directory in the top level, and the

- python/pysmurf/core/devices/_PcieCard.py
- python/pysmurf/core/roots/CmbEth.py
- python/pysmurf/core/roots/CmbPcie.py
- python/pysmurf/core/roots/Common.py
- python/pysmurf/core/roots/DevBoardEth.py
- python/pysmurf/core/roots/DevBoardPcie.py
- python/pysmurf/core/server_scripts/Common.py
- server_scripts/cmb_eth.py
- server_scripts/cmb_pcie.py
- server_scripts/dev_board_eth.py
- server_scripts/dev_board_pcie.py
https://jira.slac.stanford.edu/browse/ESCRYODET-509
> Migrate GUI to PyDM

- python/pysmurf/client/debug/smurf_noise.py
- python/pysmurf/client/tune/smurf_tune.py
- python/pysmurf/client/util/smurf_util.py
Small change that parses the mask file properly.
> Fixing bug with loading mask

- python/pysmurf/client/base/smurf_control.py
- python/pysmurf/client/command/cryo_card.py
- python/pysmurf/client/command/smurf_atca_monitor.py
- python/pysmurf/client/debug/smurf_iv.py
- python/pysmurf/client/debug/smurf_noise.py
- python/pysmurf/client/tune/smurf_tune.py
- python/pysmurf/client/util/smurf_util.py
This fixes a bad merge that slipped into master because we temporarily turned off some checks.
> Fixing bad merge in smurf_iv

- python/pysmurf/client/base/smurf_control.py
- python/pysmurf/client/util/smurf_util.py
Resolves the SmurfConfig import error in https://github.com/slaclab/pysmurf/issues/252
> Fixing SmurfConfig import error

- src/smurf/core/counters/FrameStatistics.cpp
https://jira.slac.stanford.edu/browse/ESCRYODET-583
> Change log messages to warning level, so that they don't appear by default in the console

- docker/client/Dockerfile
This fixes Ed's Jira ticket: https://jira.slac.stanford.edu/browse/ESCRYODET-590
> Add the GitPython python package to the pysmurf-client docker image

- cfg_files/ucsd/experiment_ucsd_k2so_cc02-06_lbOnlyBay0.cfg
- cfg_files/ucsd/smurf-streamer_test.cfg
- cfg_files/ucsd/ucsd_smurf_startup.cfg
- scratch/msf/dc_squid_curves.py
- scratch/msf/fast_sample_data.py
- scratch/msf/fast_sample_data_dBcperHz.py
- scratch/msf/noise_vs_NPhi0s.py
- scratch/msf/noise_vs_feedback_end_frac.py
- scratch/msf/noise_vs_feedback_start_frac.py
- scratch/msf/noise_vs_power_atten.py
- scratch/msf/noise_vs_power_drive.py
- scratch/msf/plot_squid_vs_temp.py
- scratch/msf/squid_fit.py
- scratch/shawn/scripts/init_ucsd.py
Upgraded UCSD system (smurf-srv14) from rogue3 to rogue4, porting over all their configuration scripts and scratch scripts.  Verified system booted up and configured properly (good full band response).  After this PR UCSD will be able to develop off of master.
> Synching ucsd with master

- python/pysmurf/client/base/smurf_control.py
- python/pysmurf/client/tune/smurf_tune.py
Simply exposing the relevant args
> exposing find_freq optional arguments for finding peaks

- scratch/shawn/scripts/shawnhammer.sh
This change makes it so that shawn-hammer kills possibly conflicting dockers that were started by jackhammer.
> Makes shawnhammer shutdown smurf-streamer dockers

- .travis.yml
- releaseGen.py
Please take a look. I am not sure where the proper home is. I did not attempt to integrate into Travis.
> Add release notes generation script

- releaseGen.py
This change will scan the pull request body for the #123 pattern in an attempt to find references to issues.
> Extract issue references from PR body

- scratch/eyy/test_scripts/profile_band.py
np.load needs an `allow_pickle=True` statement for saved dicts.
> Scratch update for eyy - bug in profile_band loading of .npy files

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/ISSUE_TEMPLATE/something-else.md
- .github/pull_request_template.md
This PR resolves #346 
This PR will add templates to both issues and PRs. Please find below a preview of the templates, please let me know if you want a different format, or content.
This PR resolves [introduce here issue number(s) or jira ticket(s). If there are no issues for this PR, please first open an issue for it].
A clear and concise description of what the bug is here.
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error
A clear and concise description of what you expected to happen.
Add any other details about the problem here.
A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
A clear and concise description of what you want to happen.
Add any other …
> Crate issues and PR templates

- releaseGen.py
This fixes #338 .
Fix the regular expression that matches the issue number. The issue number can be preceded by any whitespace character and followed by an space or any non-alphanumeric character.
> Fix the `releaseGen.py` to catch issues numbers that are followed by a dot.

- python/pysmurf/client/tune/smurf_tune.py
- scratch/eyy/noise/noise_summary_stanford_pole.py
This PR resolves #383 .
- Optional variable to turn off phase highlighting in find_peak plotting
- Updating eyy scratch with a pole vs stanford script.
> Introduce optional variable to turn off phase highlighting in find_peak plotting

- scratch/eyy/test_scripts/nonstop_profile_band.py
- scratch/eyy/test_scripts/profile_band.py
This PR resolves #386 .
- Moves the part of `profile_band` that actually does things into a callable function `run()`. 
- New script `nonstop_profile_band` that executes `profile_band` in an infinite loop to test stability of firmware/software
> Moves the running part of `profile_band` into a callable function. 

- README.md
No link to read the docs in the readme
Add the readthedocs html to readme
> Adding readthedocs to readme

- python/pysmurf/client/util/smurf_util.py
This PR resolves #273.
This adds a stream_data context manager to smurf_util. We'll probably want to use this in SO scripts to safely stream data while running other commands. This will make it so we don't accidentally keep streaming data if our script raises an error while streaming.
> Added streaming context manager

- cfg_files/cornell/cornell_smurf_startup.cfg
- cfg_files/cornell/experiment_cornell.cfg
- scratch/shawn/full_band_response.py
- scratch/shawn/scripts/init_cornell.py
None.
Merges latest Cornell Rogue3 configuration with Rogue3 master branch so we cal delete the cornell branch.  Adds the full_band_response.py diagnostic script to the Rogue3 master branch.
> Merging most recent Cornell configuration into Rogue3.

- python/pysmurf/client/util/smurf_util.py
This PR resolves #421 
Changes the implementation of `play_sine_tes` to allow for higher frequencies.
> Adding scaling relation for faster frequencies in play_sine_tes

- python/pysmurf/client/tune/smurf_tune.py
This PR resolves issue https://github.com/slaclab/pysmurf/issues/435.
Fixes a couple of missing fs in some fstrings in the tune submodule.
> Fixing a couple of fstrings with missing fs

- python/pysmurf/client/tune/smurf_tune.py
- python/pysmurf/client/util/smurf_util.py
This PR doesn't address any open pysmurf issues.
Fixes some issues that arose when trying to run with a new fw version with a different number of subbands and channels per subband.
> Fw refactor

- cfg_files/rflab/rflab_smurf_startup_stephen_test.cfg
- python/pysmurf/client/base/smurf_control.py
- python/pysmurf/client/command/smurf_atca_monitor.py
- scratch/stephen/full_band_response_AMCatten.py
This PR doesn't resolve any issues but adds a script that Stephen wrote to qualify AMCs.
Adds new startup cfg file for qualifying AMCs, cfg_files/rflab/rflab_smurf_startup_stephen_test.cfg.  Adds _reg suffix to all smurf_atca_monitor register path variables.  Adds new function `get_amc_asset_tag` that returns an AMC's asset tag.  Adds Stephen's AMC testing script scratch/stephen/full_band_response_AMCatten.py.
> Stephen's AMC testing script.

- requirements.txt
No existing issue.
Just adds the packaging module to requirements.txt.
> Adding packaging to requirements.txt.

- README.SmurfProcessor.md
This PR resolves #498 
Fix a broken link on **README.SmurfProcessor.md** to the Data Transmitter documentation.
> Fix broken link

- README.md
This PR resolves #502 
Fix the reference to the deprecated `master` branch to `main`.
> Update reference to the old master branch to main

- scratch/shawn/fill_band.py
This PR updates fill_band.py to support any number of subbands (remove hardcoded 128 subbands)
> Modify fill_band to support both 128 and 512 subbands

- cfg_files/rflab/experiment_so_westpak_6carrier_14day_test.cfg
- cfg_files/rflab/rflab_smurf_startup.cfg
- cfg_files/rflab/rflab_smurf_startup_stephen_test.cfg
- cfg_files/rflab/smurf_startup_6carrier.cfg
- cfg_files/rflab/smurf_startup_so_westpak_6carrier_14day_test.cfg
- cfg_files/rflab/smurf_startup_thermal_test.cfg
- python/pysmurf/client/command/smurf_atca_monitor.py
- python/pysmurf/client/command/smurf_command.py
- python/pysmurf/client/util/smurf_util.py
- scratch/shawn/fill_band.py
- scratch/shawn/full_band_response.py
- scratch/shawn/logmemory.py
- scratch/shawn/logpackets.py
- scratch/shawn/logserver.py
- scratch/shawn/plot_temperatures.sh
- scratch/shawn/thermal_test.py
- scratch/stephen/full_band_response_AMCatten.py
This PR does not resolve an open issue.
Bug fixes and script improvements for long Westpak run with 6x carriers.
> Thermal test scripts and bug fixes for long Westpak run with 6x carriers.

- scratch/shawn/fill_band.py
> Use S.get_number_sub_bands() in fill_band.py

- python/pysmurf/client/util/smurf_util.py
> Fixing doc string for get_tes_bias_bipolar_array

- python/pysmurf/client/debug/smurf_noise.py
This PR resolves #541 .
There were several plotting bugs in `analyze_noise_vs_bias` which would cause it to fail.
> Resolving bugs in analyze_noise_vs_bias

- cfg_files/nist/cmb/experiment_nistcmb_cc02-02_hbOnlyBay0.cfg
- cfg_files/nist/cmb/experiment_nistcmb_cc02-02_lbOnlyBay0.cfg
- cfg_files/nist/cmb/nist_cmb_smurf_startup.cfg
- python/pysmurf/client/debug/smurf_noise.py
- python/pysmurf/client/util/smurf_util.py
This PR resolves https://github.com/slaclab/pysmurf/issues/549.
For more details on the glitching and fix, see the issue link above.  There's also some updates to NIST's configuration files in this PR that only effects them.
> Critical fix for decode_data function that eliminates glitching seen at NIST.

- cfg_files/stanford/experiment_fp31_cc03-02_lbOnlyBay0.cfg
- python/pysmurf/client/base/smurf_control.py
- python/pysmurf/client/command/smurf_cmd.py
- python/pysmurf/client/command/smurf_command.py
- python/pysmurf/client/util/smurf_util.py
Fixes #596
`smurf_cmd.py` has not been updated since the pole deployment. Lots of broken functions. 
> Updating smurf_cmd.py

- python/pysmurf/client/util/smurf_util.py
This PR resolves #612 
Corrects doc-string for read_stream_data.
> Change units in read_stream_data

- python/pysmurf/client/tune/smurf_tune.py
This PR resolves #592.
Adds doc strings for LMS gain. Also introduces feedback_gain parameter to tracking
> Update tracking_setup, add feedback_gain and documentation

- python/pysmurf/client/debug/smurf_noise.py
This resolves #614 
Returns all the fit parameters
The dimension of the return parameter is now larger. 
> take_noise_psd return_noise_params expanding

- python/pysmurf/client/util/smurf_util.py
- scratch/yuka/get_sigma_full_band_resp_ratios.py
- scratch/yuka/loopback_test.py
- scratch/yuka/page_template/index.html
- scratch/yuka/page_template/scripts/pager.css
- scratch/yuka/page_template/scripts/pager.js
- scratch/yuka/page_template/style.css
This PR resolves #627.
Adding square wave function to smurf_util.py.
Added a function in smurf_util.py.
smurf_util.py didn't have play_square_tes.
Function play_square_tes is now in smurf_util.py.
> Tkid square wave

- .github/labeler.yml
- .github/workflows/ci-cd.yml
- README.Docker.md
- docker/server/.gitignore
- docker/server/Dockerfile
- docker/server/build.sh
- docker/server/definitions.sh
- docker/server/validate.sh
- releaseGen.py
This PR resolves [ESCRYODET-818](https://jira.slac.stanford.edu/browse/ESCRYODET-818).
Bring same changes from https://github.com/slaclab/pysmurf/pull/639 to the develop branch.
> Generate stable docker images from this repository (to develop)

- python/pysmurf/client/util/tkid_util.py
This PR resolves #635 
Add new file with TKID mixin class.
New file in client/util
None
New file in client/util
> TKID mixin file for TKID specific functions

- python/pysmurf/client/util/smurf_util.py
This PR resolves #668 
Adds extra keyword arguments to the stream_data_on function to set the channel mask manually, disable dat_files, and extend the time after filter reset.
> Streaming enhancements

- python/pysmurf/client/command/smurf_command.py
- python/pysmurf/client/util/dscounters.py
This modifies the set_downsample_factor function so that it will set the external bitmask if the downsampling mode is external.
It also adds Matthew's dscounters module to pysmurf.client.util.
> set_downsample_factor with external downsampling

- python/pysmurf/client/command/smurf_command.py
- python/pysmurf/client/util/dscounters.py
Fixes the `period_from_mask` function and changes `get_downsample_factor` to work in external mode
> Fix get period from mask

- python/pysmurf/client/tune/smurf_tune.py
Passes `show_plot` and `save_plot` keywords to `find_all_peak` in `smurf_tune` from `find_freq`.
> Pass show_plot and save_plot vals to find_all_peak

- python/pysmurf/client/command/smurf_command.py
- python/pysmurf/client/util/smurf_util.py
- scratch/eyy/test_scripts/profile_slot.py
Minor bug fixes for some small issues that cropped up after upgrading Ubuntu and software in the pysmurf client docker.
> Minor bug fixes.

- docker/server/scripts/server_common.sh
Simple fix for https://github.com/slaclab/pysmurf/issues/809.
> Bash typo fix.
